In [13]:
import pandas as pd
import numpy as np

df=pd.read_csv('../data/hospital_raw_data.csv')
df.head()

,Case_No,DoctorLicense,Month,Insurance_Payer,Case_Type,LOS,Severity,Revenue,DOB,Nationality,Gender,DoctorName,Specialty,Doctor_Type,Doctor_Status,CMI_Value
0,12300001,DOC045,1/1/2025,Self-Pay,DC,9,2,5210.31,1992,India,M,Doctor_45,Orthopaedics,Consultant,Active,1.256
1,12300002,DOC025,1/1/2025,Nextcare Insurance,IP,11,2,28424.85,1980,India,F,Doctor_25,Emergency,Specialist,Inactive,1.409
2,12300003,DOC033,1/1/2025,Nextcare Insurance,IP,5,1,19889.67,1997,UAE,M,Doctor_33,Internal Medicine,GP,Active,1.052
3,12300004,DOC038,1/1/2025,Self-Pay,OP,0,2,3931.25,1966,UK,F,Doctor_38,Emergency,Consultant,Active,0.875
4,12300005,DOC020,1/1/2025,PureWin Insurance,DC,3,2,9998.23,1988,India,M,Doctor_20,Cardiology,Consultant,Active,0.973

In [14]:
df=df.rename(columns={'DOB':'Birth_Year'})
df['Age'] = 2026 - df['Birth_Year']
df['Gender'] = df['Gender'].replace({'M':'Male','F':'Female'})
df['InsurancePlanName'] = 'Standard'
df['Payer_Mix'] = np.where(df['Insurance_Payer'] == 'Self-Pay', 'Self-Pay', 'Insurance')
df['Surgical_Mix'] = 'Medical' 
df['Discharge_Time'] = 'Not Applicable'
df['Discharge_Before_12PM'] = 'Not Applicable'
df.head()

,Case_No,DoctorLicense,Month,Insurance_Payer,Case_Type,LOS,Severity,Revenue,Birth_Year,Nationality,...,Specialty,Doctor_Type,Doctor_Status,CMI_Value,Age,InsurancePlanName,Payer_Mix,Surgical_Mix,Discharge_Time,Discharge_Before_12PM
0,12300001,DOC045,1/1/2025,Self-Pay,DC,9,2,5210.31,1992,India,...,Orthopaedics,Consultant,Active,1.256,34,Standard,Self-Pay,Medical,Not Applicable,Not Applicable
1,12300002,DOC025,1/1/2025,Nextcare Insurance,IP,11,2,28424.85,1980,India,...,Emergency,Specialist,Inactive,1.409,46,Standard,Insurance,Medical,Not Applicable,Not Applicable
2,12300003,DOC033,1/1/2025,Nextcare Insurance,IP,5,1,19889.67,1997,UAE,...,Internal Medicine,GP,Active,1.052,29,Standard,Insurance,Medical,Not Applicable,Not Applicable
3,12300004,DOC038,1/1/2025,Self-Pay,OP,0,2,3931.25,1966,UK,...,Emergency,Consultant,Active,0.875,60,Standard,Self-Pay,Medical,Not Applicable,Not Applicable
4,12300005,DOC020,1/1/2025,PureWin Insurance,DC,3,2,9998.23,1988,India,...,Cardiology,Consultant,Active,0.973,38,Standard,Insurance,Medical,Not Applicable,Not Applicable

In [15]:
print("\n--- Data Quality Check ---")
total_records = len(df)
duplicate_count = df.duplicated(subset=['Case_No']).sum()
missing_values_count = df.isnull().any(axis=1).sum()
duplicate_error_pct = (duplicate_count / total_records) * 100
missing_error_pct = (missing_values_count / total_records) * 100
print(f"Total Records Before Cleaning: {total_records}")
print(f"Duplicate Records Found: {duplicate_count} ({duplicate_error_pct:.2f}%)")
print(f"Rows with Missing Values: {missing_values_count} ({missing_error_pct:.2f}%)")
print("--------------------------\n")

--- Data Quality Check ---
Total Records Before Cleaning: 10000
Duplicate Records Found: 5 (0.05%)
Rows with Missing Values: 0 (0.00%)
--------------------------

In [17]:
df = df.drop_duplicates(subset=['Case_No'], keep='first')
df['Duplicate_Case_Flag'] = 'No'
total_records_after_dedup = len(df)
print(f"Total Records After Deduplication: {total_records_after_dedup}")

Total Records After Deduplication: 9995

In [21]:
final_columns = [
    'Month', 'Case_No', 'Birth_Year', 'Age', 'Nationality', 'Gender', 
    'DoctorLicense', 'DoctorName', 'Doctor_Type', 'Doctor_Status', 
    'CMI_Value', 'Specialty', 'Insurance_Payer', 'InsurancePlanName', 
    'Payer_Mix', 'Case_Type', 'LOS', 'Severity', 'Surgical_Mix', 
    'Revenue'
]

df_final = df[final_columns]

print("Saving cleaned dataset...")
output_path = '../data/hospital_data_AFTER_cleaning.csv'
df_final.to_csv(output_path, index=False)
print(f"Cleaned dataset saved to {output_path}")

Saving cleaned dataset...
Cleaned dataset saved to ../data/hospital_data_AFTER_cleaning.csv