In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("hospital Analytics enviornment is ready!")

hospital Analytics enviornment is ready!

In [2]:
import os
import pandas as pd

data_path = "data/raw"

files = [file for file in os.listdir(data_path) if file.endswith(".csv")]

print("Number of CSV files found:", len(files))
print("\nFiles found:")

for file in sorted(files):
    print(file)

Number of CSV files found: 19

Files found:
admission.csv
bed.csv
billing.csv
billing_detail.csv
department.csv
diagnostic_test.csv
disease.csv
doctor.csv
drug.csv
drug_inventory.csv
drug_manufacturer.csv
employee.csv
insurance_provider.csv
patient.csv
patient_diagnostic.csv
patient_insurance.csv
prescription.csv
staff_assignment.csv
ward.csv

In [3]:
import os
import pandas as pd

data_path = "data/raw"

summary = []

for file in sorted(os.listdir(data_path)):
    if file.endswith(".csv"):
        file_path = os.path.join(data_path, file)
        df = pd.read_csv(file_path)

        summary.append({
            "File": file,
            "Rows": df.shape[0],
            "Columns": df.shape[1]
        })

summary_df = pd.DataFrame(summary)

summary_df

                      File    Rows  Columns
0            admission.csv   45000       10
1                  bed.csv     415        4
2              billing.csv   45000        8
3       billing_detail.csv  112402        5
4           department.csv      11        5
5      diagnostic_test.csv       9        5
6              disease.csv      20        3
7               doctor.csv      98        5
8                 drug.csv     250        6
9       drug_inventory.csv     250        6
10   drug_manufacturer.csv     300        5
11            employee.csv     500        7
12  insurance_provider.csv      50        5
13             patient.csv   30000        6
14  patient_diagnostic.csv   63269        6
15   patient_insurance.csv   21617        7
16        prescription.csv   73109        6
17    staff_assignment.csv     207        4
18                ward.csv      27        5

In [4]:
for file in sorted(os.listdir(data_path)):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(data_path, file))
        
        print("\n" + "=" * 70)
        print(file)
        print("=" * 70)
        print("Columns:")
        print(list(df.columns))

======================================================================
admission.csv
======================================================================
Columns:
['admission_id', 'admission_date', 'discharge_date', 'admission_type', 'admission_status', 'patient_id', 'department_id', 'ward_id', 'bed_id', 'disease_id']

======================================================================
bed.csv
======================================================================
Columns:
['bed_id', 'bed_number', 'bed_status', 'ward_id']

======================================================================
billing.csv
======================================================================
Columns:
['bill_id', 'bill_date', 'total_amount', 'insurance_covered_amount', 'patient_payable_amount', 'payment_status', 'payment_mode', 'admission_id']

======================================================================
billing_detail.csv
======================================================================
Columns:
['billing_detail_id', 'charge_type', 'reference_id', 'amount', 'bill_id']

======================================================================
department.csv
======================================================================
Columns:
['department_id', 'department_name', 'department_type', 'floor_number', 'status']

======================================================================
diagnostic_test.csv
======================================================================
Columns:
['test_id', 'test_name', 'test_category', 'standard_cost', 'department_id']

======================================================================
disease.csv
======================================================================
Columns:
['disease_id', 'disease_name', 'disease_category']

======================================================================
doctor.csv
======================================================================
Columns:
['doctor_id', 'employee_id', 'specialization', 'qualification', 'experience_years']

======================================================================
drug.csv
======================================================================
Columns:
['drug_id', 'drug_name', 'brand_name', 'drug_category', 'unit_cost', 'manufacturer_id']

======================================================================
drug_inventory.csv
======================================================================
Columns:
['inventory_id', 'current_stock', 'reorder_level', 'inventory_status', 'last_restock_date', 'drug_id']

======================================================================
drug_manufacturer.csv
======================================================================
Columns:
['manufacturer_id', 'manufacturer_name', 'country', 'reliability_rating', 'contract_status']

======================================================================
employee.csv
======================================================================
Columns:
['employee_id', 'employee_name', 'gender', 'role', 'employment_type', 'date_of_joining', 'department_id']

======================================================================
insurance_provider.csv
======================================================================
Columns:
['insurance_provider_id', 'provider_name', 'provider_type', 'contact_details', 'coverage_limit']

======================================================================
patient.csv
======================================================================
Columns:
['patient_id', 'gender', 'date_of_birth', 'blood_group', 'city', 'contact_number']

======================================================================
patient_diagnostic.csv
======================================================================
Columns:
['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']

======================================================================
patient_insurance.csv
======================================================================
Columns:
['patient_insurance_id', 'policy_number', 'coverage_percentage', 'policy_start_date', 'policy_end_date', 'patient_id', 'insurance_provider_id']

======================================================================
prescription.csv
======================================================================
Columns:
['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']

======================================================================
staff_assignment.csv
======================================================================
Columns:
['assignment_id', 'employee_id', 'ward_id', 'shift']

======================================================================
ward.csv
======================================================================
Columns:
['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

In [5]:
for file in sorted(os.listdir(data_path)):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(data_path, file))

        print("\n" + "=" * 80)
        print(f"FILE: {file}")
        print("=" * 80)

        print("\nShape:", df.shape)

        print("\nData Types:")
        print(df.dtypes)

        print("\nMissing Values:")
        print(df.isnull().sum())

        print("\nDuplicate Rows:", df.duplicated().sum())

================================================================================
FILE: admission.csv
================================================================================

Shape: (45000, 10)

Data Types:
admission_id        int64
admission_date        str
discharge_date        str
admission_type        str
admission_status      str
patient_id          int64
department_id       int64
ward_id             int64
bed_id              int64
disease_id          int64
dtype: object

Missing Values:
admission_id        0
admission_date      0
discharge_date      0
admission_type      0
admission_status    0
patient_id          0
department_id       0
ward_id             0
bed_id              0
disease_id          0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: bed.csv
================================================================================

Shape: (415, 4)

Data Types:
bed_id        int64
bed_number      str
bed_status      str
ward_id       int64
dtype: object

Missing Values:
bed_id        0
bed_number    0
bed_status    0
ward_id       0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: billing.csv
================================================================================

Shape: (45000, 8)

Data Types:
bill_id                       int64
bill_date                       str
total_amount                  int64
insurance_covered_amount    float64
patient_payable_amount      float64
payment_status                  str
payment_mode                    str
admission_id                  int64
dtype: object

Missing Values:
bill_id                     0
bill_date                   0
total_amount                0
insurance_covered_amount    0
patient_payable_amount      0
payment_status              0
payment_mode                0
admission_id                0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: billing_detail.csv
================================================================================

Shape: (112402, 5)

Data Types:
billing_detail_id      int64
charge_type              str
reference_id         float64
amount                 int64
bill_id                int64
dtype: object

Missing Values:
billing_detail_id        0
charge_type              0
reference_id         67402
amount                   0
bill_id                  0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: department.csv
================================================================================

Shape: (11, 5)

Data Types:
department_id      int64
department_name      str
department_type      str
floor_number       int64
status               str
dtype: object

Missing Values:
department_id      0
department_name    0
department_type    0
floor_number       0
status             0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: diagnostic_test.csv
================================================================================

Shape: (9, 5)

Data Types:
test_id          int64
test_name          str
test_category      str
standard_cost    int64
department_id    int64
dtype: object

Missing Values:
test_id          0
test_name        0
test_category    0
standard_cost    0
department_id    0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: disease.csv
================================================================================

Shape: (20, 3)

Data Types:
disease_id          int64
disease_name          str
disease_category      str
dtype: object

Missing Values:
disease_id          0
disease_name        0
disease_category    0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: doctor.csv
================================================================================

Shape: (98, 5)

Data Types:
doctor_id           int64
employee_id         int64
specialization        str
qualification         str
experience_years    int64
dtype: object

Missing Values:
doctor_id           0
employee_id         0
specialization      0
qualification       0
experience_years    0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: drug.csv
================================================================================

Shape: (250, 6)

Data Types:
drug_id            int64
drug_name            str
brand_name           str
drug_category        str
unit_cost          int64
manufacturer_id    int64
dtype: object

Missing Values:
drug_id            0
drug_name          0
brand_name         0
drug_category      0
unit_cost          0
manufacturer_id    0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: drug_inventory.csv
================================================================================

Shape: (250, 6)

Data Types:
inventory_id         int64
current_stock        int64
reorder_level        int64
inventory_status       str
last_restock_date      str
drug_id              int64
dtype: object

Missing Values:
inventory_id         0
current_stock        0
reorder_level        0
inventory_status     0
last_restock_date    0
drug_id              0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: drug_manufacturer.csv
================================================================================

Shape: (300, 5)

Data Types:
manufacturer_id         int64
manufacturer_name         str
country                   str
reliability_rating    float64
contract_status           str
dtype: object

Missing Values:
manufacturer_id       0
manufacturer_name     0
country               0
reliability_rating    0
contract_status       0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: employee.csv
================================================================================

Shape: (500, 7)

Data Types:
employee_id        int64
employee_name        str
gender               str
role                 str
employment_type      str
date_of_joining      str
department_id      int64
dtype: object

Missing Values:
employee_id        0
employee_name      0
gender             0
role               0
employment_type    0
date_of_joining    0
department_id      0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: insurance_provider.csv
================================================================================

Shape: (50, 5)

Data Types:
insurance_provider_id    int64
provider_name              str
provider_type              str
contact_details          int64
coverage_limit           int64
dtype: object

Missing Values:
insurance_provider_id    0
provider_name            0
provider_type            0
contact_details          0
coverage_limit           0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: patient.csv
================================================================================

Shape: (30000, 6)

Data Types:
patient_id        int64
gender              str
date_of_birth       str
blood_group         str
city                str
contact_number      str
dtype: object

Missing Values:
patient_id        0
gender            0
date_of_birth     0
blood_group       0
city              0
contact_number    0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: patient_diagnostic.csv
================================================================================

Shape: (63269, 6)

Data Types:
patient_diagnostic_id    int64
test_date                  str
result_status              str
admission_id             int64
test_id                  int64
doctor_id                int64
dtype: object

Missing Values:
patient_diagnostic_id    0
test_date                0
result_status            0
admission_id             0
test_id                  0
doctor_id                0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: patient_insurance.csv
================================================================================

Shape: (21617, 7)

Data Types:
patient_insurance_id     int64
policy_number              str
coverage_percentage      int64
policy_start_date          str
policy_end_date            str
patient_id               int64
insurance_provider_id    int64
dtype: object

Missing Values:
patient_insurance_id     0
policy_number            0
coverage_percentage      0
policy_start_date        0
policy_end_date          0
patient_id               0
insurance_provider_id    0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: prescription.csv
================================================================================

Shape: (73109, 6)

Data Types:
prescription_id    int64
dosage               str
frequency            str
duration_days      int64
admission_id       int64
drug_id            int64
dtype: object

Missing Values:
prescription_id    0
dosage             0
frequency          0
duration_days      0
admission_id       0
drug_id            0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: staff_assignment.csv
================================================================================

Shape: (207, 4)

Data Types:
assignment_id    int64
employee_id      int64
ward_id          int64
shift              str
dtype: object

Missing Values:
assignment_id    0
employee_id      0
ward_id          0
shift            0
dtype: int64

Duplicate Rows: 0

================================================================================
FILE: ward.csv
================================================================================

Shape: (27, 5)

Data Types:
ward_id          int64
ward_name          str
ward_type          str
total_beds       int64
department_id    int64
dtype: object

Missing Values:
ward_id          0
ward_name        0
ward_type        0
total_beds       0
department_id    0
dtype: int64

Duplicate Rows: 0

In [6]:
# Load the important tables
patient = pd.read_csv("data/raw/patient.csv")
admission = pd.read_csv("data/raw/admission.csv")
billing = pd.read_csv("data/raw/billing.csv")
billing_detail = pd.read_csv("data/raw/billing_detail.csv")

# Check uniqueness of important ID columns
print("PATIENT IDs")
print("Total patient rows:", len(patient))
print("Unique patient IDs:", patient["patient_id"].nunique())

print("\nADMISSION IDs")
print("Total admission rows:", len(admission))
print("Unique admission IDs:", admission["admission_id"].nunique())

print("\nBILL IDs")
print("Total billing rows:", len(billing))
print("Unique bill IDs:", billing["bill_id"].nunique())

print("\nBILLING DETAIL IDs")
print("Total billing detail rows:", len(billing_detail))
print("Unique billing detail IDs:", billing_detail["billing_detail_id"].nunique())

PATIENT IDs
Total patient rows: 30000
Unique patient IDs: 30000

ADMISSION IDs
Total admission rows: 45000
Unique admission IDs: 45000

BILL IDs
Total billing rows: 45000
Unique bill IDs: 45000

BILLING DETAIL IDs
Total billing detail rows: 112402
Unique billing detail IDs: 112402

In [7]:
print("Patient IDs in admissions that don't exist in patient table:",
      (~admission["patient_id"].isin(patient["patient_id"])).sum())

print("Admission IDs in billing that don't exist in admission table:",
      (~billing["admission_id"].isin(admission["admission_id"])).sum())

print("Bill IDs in billing_detail that don't exist in billing table:",
      (~billing_detail["bill_id"].isin(billing["bill_id"])).sum())

Patient IDs in admissions that don't exist in patient table: 0
Admission IDs in billing that don't exist in admission table: 0
Bill IDs in billing_detail that don't exist in billing table: 0

In [8]:
print("Admission dates:")
print(admission["admission_date"].head())

print("\nDischarge dates:")
print(admission["discharge_date"].head())

print("\nBilling dates:")
print(billing["bill_date"].head())

print("\nDate of birth:")
print(patient["date_of_birth"].head())

Admission dates:
0    2020-02-25
1    2022-02-22
2    2021-02-03
3    2021-12-31
4    2022-07-02
Name: admission_date, dtype: str

Discharge dates:
0    2020-02-27
1    2022-03-04
2    2021-02-09
3    2022-01-05
4    2022-07-07
Name: discharge_date, dtype: str

Billing dates:
0    2025-05-26
1    2023-11-19
2    2023-02-20
3    2021-09-01
4    2021-07-13
Name: bill_date, dtype: str

Date of birth:
0    1987-08-24
1    1960-05-18
2    1955-04-24
3    2004-06-16
4    1977-07-22
Name: date_of_birth, dtype: str

In [9]:
# Convert date columns to datetime format

admission["admission_date"] = pd.to_datetime(admission["admission_date"])
admission["discharge_date"] = pd.to_datetime(admission["discharge_date"])

billing["bill_date"] = pd.to_datetime(billing["bill_date"])

patient["date_of_birth"] = pd.to_datetime(patient["date_of_birth"])

print("Date columns converted successfully!")

Date columns converted successfully!

In [10]:
print("Admission date type:", admission["admission_date"].dtype)
print("Discharge date type:", admission["discharge_date"].dtype)
print("Billing date type:", billing["bill_date"].dtype)
print("Date of birth type:", patient["date_of_birth"].dtype)

Admission date type: datetime64[us]
Discharge date type: datetime64[us]
Billing date type: datetime64[us]
Date of birth type: datetime64[us]

In [11]:
invalid_dates = admission[
    admission["discharge_date"] < admission["admission_date"]
]

print("Records where discharge is before admission:", len(invalid_dates))

Records where discharge is before admission: 0

In [12]:
length_of_stay = (
    admission["discharge_date"] - admission["admission_date"]
).dt.days

print("Minimum stay:", length_of_stay.min(), "days")
print("Maximum stay:", length_of_stay.max(), "days")
print("Average stay:", round(length_of_stay.mean(), 2), "days")

Minimum stay: 1 days
Maximum stay: 15 days
Average stay: 5.16 days

In [13]:
categorical_columns = {
    "admission.csv": ["admission_type", "admission_status"],
    "patient.csv": ["gender", "blood_group"],
    "billing.csv": ["payment_status", "payment_mode"]
}

tables = {
    "admission.csv": admission,
    "patient.csv": patient,
    "billing.csv": billing
}

for file, columns in categorical_columns.items():
    print("\n" + "=" * 70)
    print(file)
    print("=" * 70)

    df = tables[file]

    for column in columns:
        print(f"\n{column}:")
        print(df[column].value_counts(dropna=False))

======================================================================
admission.csv
======================================================================

admission_type:
admission_type
Elective     26923
Emergency    18077
Name: count, dtype: int64

admission_status:
admission_status
Discharged    45000
Name: count, dtype: int64

======================================================================
patient.csv
======================================================================

gender:
gender
Male      15918
Female    13478
Other       604
Name: count, dtype: int64

blood_group:
blood_group
O+     3851
AB-    3839
O-     3792
A-     3779
AB+    3752
A+     3730
B+     3695
B-     3562
Name: count, dtype: int64

======================================================================
billing.csv
======================================================================

payment_status:
payment_status
Pending    22670
Paid       22330
Name: count, dtype: int64

payment_mode:
payment_mode
Insurance    35979
UPI           3049
Card          3017
Cash          2955
Name: count, dtype: int64

In [14]:
billing["calculated_total"] = (
    billing["insurance_covered_amount"] +
    billing["patient_payable_amount"]
)

billing["amount_difference"] = (
    billing["total_amount"] - billing["calculated_total"]
)

print("Records checked:", len(billing))
print(
    "Records where amounts don't match:",
    (billing["amount_difference"].abs() > 0.01).sum()
)

print(
    "Largest difference:",
    billing["amount_difference"].abs().max()
)

Records checked: 45000
Records where amounts don't match: 0
Largest difference: 0.0

In [15]:
# How many admissions does each patient have?
admissions_per_patient = admission.groupby("patient_id").size()

print("Patients with at least one admission:",
      admissions_per_patient.size)

print("Patients with multiple admissions:",
      (admissions_per_patient > 1).sum())

print("Maximum admissions for one patient:",
      admissions_per_patient.max())


# How many billing details does each bill have?
details_per_bill = billing_detail.groupby("bill_id").size()

print("\nBills with at least one billing detail:",
      details_per_bill.size)

print("Bills with multiple billing details:",
      (details_per_bill > 1).sum())

print("Maximum details for one bill:",
      details_per_bill.max())

Patients with at least one admission: 23275
Patients with multiple admissions: 13248
Maximum admissions for one patient: 8

Bills with at least one billing detail: 45000
Bills with multiple billing details: 40262
Maximum details for one bill: 4

In [16]:
print("=== BILLING AMOUNTS ===")

print("\nTotal Amount:")
print(billing["total_amount"].describe())

print("\nInsurance Covered Amount:")
print(billing["insurance_covered_amount"].describe())

print("\nPatient Payable Amount:")
print(billing["patient_payable_amount"].describe())

print("\nNegative values:")
print("Total amount:",
      (billing["total_amount"] < 0).sum())

print("Insurance covered:",
      (billing["insurance_covered_amount"] < 0).sum())

print("Patient payable:",
      (billing["patient_payable_amount"] < 0).sum())

=== BILLING AMOUNTS ===

Total Amount:
count    45000.000000
mean     37427.691311
std      20898.321091
min       5001.000000
25%      21231.000000
50%      34623.500000
75%      48039.250000
max      89990.000000
Name: total_amount, dtype: float64

Insurance Covered Amount:
count    45000.000000
mean     21708.463711
std      18289.872062
min          0.000000
25%       6580.000000
50%      19210.500000
75%      32752.325000
max      80956.800000
Name: insurance_covered_amount, dtype: float64

Patient Payable Amount:
count    45000.000000
mean     15719.227600
std      16216.113367
min        500.300000
25%       4743.850000
50%       9712.150000
75%      20746.750000
max      89921.000000
Name: patient_payable_amount, dtype: float64

Negative values:
Total amount: 0
Insurance covered: 0
Patient payable: 0

In [17]:
# Load the related tables
department = pd.read_csv("data/raw/department.csv")
ward = pd.read_csv("data/raw/ward.csv")
bed = pd.read_csv("data/raw/bed.csv")
disease = pd.read_csv("data/raw/disease.csv")

# Check whether admission IDs match the related tables
print("Department IDs not found:",
      (~admission["department_id"].isin(department["department_id"])).sum())

print("Ward IDs not found:",
      (~admission["ward_id"].isin(ward["ward_id"])).sum())

print("Bed IDs not found:",
      (~admission["bed_id"].isin(bed["bed_id"])).sum())

print("Disease IDs not found:",
      (~admission["disease_id"].isin(disease["disease_id"])).sum())

Department IDs not found: 0
Ward IDs not found: 0
Bed IDs not found: 0
Disease IDs not found: 0

In [18]:
print("=== DEPARTMENTS ===")
print(department)

print("\n=== WARDS ===")
print(ward)

print("\n=== DISEASES ===")
print(disease.head(20))

print("\n=== BEDS ===")
print(bed.head(20))

=== DEPARTMENTS ===
    department_id    department_name department_type  floor_number  status
0               1          Emergency        Clinical             0  Active
1               2  Internal Medicine        Clinical             2  Active
2               3            Surgery        Clinical             3  Active
3               4         Pediatrics        Clinical             2  Active
4               5        Orthopedics        Clinical             4  Active
5               6                ICU        Clinical             1  Active
6               7          Radiology      Diagnostic             1  Active
7               8          Pathology      Diagnostic             1  Active
8               9           Pharmacy           Admin             0  Active
9              10            Billing           Admin             0  Active
10             11                 HR           Admin             0  Active

=== WARDS ===
    ward_id                 ward_name     ward_type  total_beds  department_id
0         1          Emergency Ward 1       General          10              1
1         2          Emergency Ward 2       Private          15              1
2         3          Emergency Ward 3       General          10              1
3         4          Emergency Ward 4       General          20              1
4         5          Emergency Ward 5       General          20              1
5         6  Internal Medicine Ward 1       Private          10              2
6         7  Internal Medicine Ward 2       Private          15              2
7         8  Internal Medicine Ward 3       General          10              2
8         9  Internal Medicine Ward 4       General          10              2
9        10  Internal Medicine Ward 5       General          20              2
10       11            Surgery Ward 1       General          20              3
11       12            Surgery Ward 2       General          20              3
12       13            Surgery Ward 3       Private          20              3
13       14            Surgery Ward 4       Private          15              3
14       15            Surgery Ward 5       General          15              3
15       16         Pediatrics Ward 1  Semi-Private          10              4
16       17         Pediatrics Ward 2       General          20              4
17       18         Pediatrics Ward 3  Semi-Private          15              4
18       19         Pediatrics Ward 4  Semi-Private          10              4
19       20         Pediatrics Ward 5       General          15              4
20       21        Orthopedics Ward 1       General          15              5
21       22        Orthopedics Ward 2       General          15              5
22       23        Orthopedics Ward 3  Semi-Private          20              5
23       24                ICU Ward 1           ICU          10              6
24       25                ICU Ward 2           ICU          20              6
25       26                ICU Ward 3           ICU          15              6
26       27                ICU Ward 4           ICU          20              6

=== DISEASES ===
    disease_id                           disease_name disease_category
0            1            Acute Myocardial Infarction          Cardiac
1            2                                 Stroke     Neurological
2            3                  Road Traffic Accident           Trauma
3            4                                 Sepsis       Infectious
4            5             Acute Respiratory Distress      Respiratory
5            6                      Diabetes Mellitus        Endocrine
6            7                           Hypertension          Cardiac
7            8                 Chronic Kidney Disease            Renal
8            9  Chronic Obstructive Pulmonary Disease      Respiratory
9           10                                 Anemia    Hematological
10          11                         Fracture Femur       Orthopedic
11          12                           Appendicitis         Surgical
12          13                             Gallstones         Surgical
13          14                                 Hernia         Surgical
14          15                              Pneumonia        Pediatric
15          16                      Neonatal Jaundice        Pediatric
16          17                Urinary Tract Infection       Infectious
17          18                            Viral Fever       Infectious
18          19                               COVID-19       Infectious
19          20                           Tuberculosis       Infectious

=== BEDS ===
    bed_id bed_number bed_status  ward_id
0        1        1-1   Occupied        1
1        2        1-2   Occupied        1
2        3        1-3  Available        1
3        4        1-4   Occupied        1
4        5        1-5   Occupied        1
5        6        1-6   Occupied        1
6        7        1-7  Available        1
7        8        1-8  Available        1
8        9        1-9  Available        1
9       10       1-10   Occupied        1
10      11        2-1  Available        2
11      12        2-2  Available        2
12      13        2-3  Available        2
13      14        2-4   Occupied        2
14      15        2-5   Occupied        2
15      16        2-6   Occupied        2
16      17        2-7  Available        2
17      18        2-8  Available        2
18      19        2-9   Occupied        2
19      20       2-10   Occupied        2

In [19]:
# Count actual beds in each ward
actual_beds = (
    bed.groupby("ward_id")
       .size()
       .reset_index(name="actual_bed_count")
)

# Compare with the total_beds recorded in ward.csv
bed_check = ward[
    ["ward_id", "ward_name", "total_beds"]
].merge(
    actual_beds,
    on="ward_id",
    how="left"
)

bed_check["difference"] = (
    bed_check["total_beds"] - bed_check["actual_bed_count"]
)

bed_check

,ward_id,ward_name,total_beds,actual_bed_count,difference
0,1,Emergency Ward 1,10,10,0
1,2,Emergency Ward 2,15,15,0
2,3,Emergency Ward 3,10,10,0
3,4,Emergency Ward 4,20,20,0
4,5,Emergency Ward 5,20,20,0
5,6,Internal Medicine Ward 1,10,10,0
6,7,Internal Medicine Ward 2,15,15,0
7,8,Internal Medicine Ward 3,10,10,0
8,9,Internal Medicine Ward 4,10,10,0
9,10,Internal Medicine Ward 5,20,20,0
10,11,Surgery Ward 1,20,20,0
11,12,Surgery Ward 2,20,20,0
12,13,Surgery Ward 3,20,20,0
13,14,Surgery Ward 4,15,15,0
14,15,Surgery Ward 5,15,15,0
15,16,Pediatrics Ward 1,10,10,0
16,17,Pediatrics Ward 2,20,20,0
17,18,Pediatrics Ward 3,15,15,0
18,19,Pediatrics Ward 4,10,10,0
19,20,Pediatrics Ward 5,15,15,0
20,21,Orthopedics Ward 1,15,15,0
21,22,Orthopedics Ward 2,15,15,0
22,23,Orthopedics Ward 3,20,20,0
23,24,ICU Ward 1,10,10,0
24,25,ICU Ward 2,20,20,0
25,26,ICU Ward 3,15,15,0
26,27,ICU Ward 4,20,20,0

In [20]:
# Check bed status values
print("Bed Status Counts:")
print(bed["bed_status"].value_counts())

# Calculate occupancy
total_beds = len(bed)
occupied_beds = (bed["bed_status"] == "Occupied").sum()
available_beds = (bed["bed_status"] == "Available").sum()

occupancy_rate = (occupied_beds / total_beds) * 100

print("\nTotal beds:", total_beds)
print("Occupied beds:", occupied_beds)
print("Available beds:", available_beds)
print("Bed occupancy rate:", round(occupancy_rate, 2), "%")

Bed Status Counts:
bed_status
Occupied     270
Available    145
Name: count, dtype: int64

Total beds: 415
Occupied beds: 270
Available beds: 145
Bed occupancy rate: 65.06 %

In [21]:
print("Reference ID missing by charge type:")
print(
    billing_detail.groupby("charge_type")["reference_id"]
    .apply(lambda x: x.isna().sum())
)

print("\nTotal records by charge type:")
print(
    billing_detail["charge_type"].value_counts()
)

print("\nMissing percentage by charge type:")
print(
    billing_detail.groupby("charge_type")["reference_id"]
    .apply(lambda x: round(x.isna().mean() * 100, 2))
)

Reference ID missing by charge type:
charge_type
Drug         31344
Procedure    13575
Room             0
Test         22483
Name: reference_id, dtype: int64

Total records by charge type:
charge_type
Room         45000
Drug         31344
Test         22483
Procedure    13575
Name: count, dtype: int64

Missing percentage by charge type:
charge_type
Drug         100.0
Procedure    100.0
Room           0.0
Test         100.0
Name: reference_id, dtype: float64

In [22]:
room_details = billing_detail[
    billing_detail["charge_type"] == "Room"
]

print("Room records:", len(room_details))
print("Missing Room reference IDs:",
      room_details["reference_id"].isna().sum())

print("\nUnique Room reference IDs:",
      room_details["reference_id"].nunique())

print("\nSample Room reference IDs:")
print(room_details["reference_id"].head(10))

Room records: 45000
Missing Room reference IDs: 0

Unique Room reference IDs: 145

Sample Room reference IDs:
0      76.0
2     302.0
6      11.0
9     128.0
10    157.0
11    143.0
13     79.0
14    276.0
17     55.0
20     11.0
Name: reference_id, dtype: float64

In [23]:
room_reference_ids = set(
    billing_detail.loc[
        billing_detail["charge_type"] == "Room",
        "reference_id"
    ].dropna().astype(int)
)

print("Room reference IDs:", len(room_reference_ids))

print(
    "Matching bed IDs:",
    len(room_reference_ids.intersection(set(bed["bed_id"])))
)

print(
    "Matching ward IDs:",
    len(room_reference_ids.intersection(set(ward["ward_id"])))
)

print(
    "Matching department IDs:",
    len(room_reference_ids.intersection(set(department["department_id"])))
)

Room reference IDs: 145
Matching bed IDs: 145
Matching ward IDs: 11
Matching department IDs: 5

In [24]:
# Connect billing details to admissions
room_check = (
    billing_detail[billing_detail["charge_type"] == "Room"]
    .merge(
        billing[["bill_id", "admission_id"]],
        on="bill_id",
        how="left"
    )
    .merge(
        admission[["admission_id", "bed_id"]],
        on="admission_id",
        how="left"
    )
)

# Compare room reference_id with the admission's bed_id
room_check["bed_match"] = (
    room_check["reference_id"].astype(int)
    == room_check["bed_id"]
)

print("Room records checked:", len(room_check))
print("Room reference matches admission bed:",
      room_check["bed_match"].sum())

print("Room reference DOES NOT match admission bed:",
      (~room_check["bed_match"]).sum())

Room records checked: 45000
Room reference matches admission bed: 45000
Room reference DOES NOT match admission bed: 0

In [25]:
import os

clean_path = "data/clean"

os.makedirs(clean_path, exist_ok=True)

print("Clean data folder created successfully!")

Clean data folder created successfully!

In [26]:
# Load the raw patient data
patient_clean = pd.read_csv("data/raw/patient.csv")

# 1. Standardize column names
patient_clean.columns = (
    patient_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# 2. Remove accidental whitespace from text columns
text_columns = patient_clean.select_dtypes(include=["object", "str"]).columns

for column in text_columns:
    patient_clean[column] = patient_clean[column].str.strip()

# 3. Convert date of birth to datetime
patient_clean["date_of_birth"] = pd.to_datetime(
    patient_clean["date_of_birth"],
    errors="coerce"
)

# 4. Ensure patient_id is integer
patient_clean["patient_id"] = patient_clean["patient_id"].astype("int64")

# 5. Check for missing values after cleaning
print("Missing values:")
print(patient_clean.isnull().sum())

# 6. Check duplicates
print("\nDuplicate rows:", patient_clean.duplicated().sum())

# 7. Save cleaned dataset
patient_clean.to_csv(
    "data/clean/patient_clean.csv",
    index=False
)

print("\nPatient dataset cleaned and saved successfully!")
print("Shape:", patient_clean.shape)

Missing values:
patient_id        0
gender            0
date_of_birth     0
blood_group       0
city              0
contact_number    0
dtype: int64

Duplicate rows: 0

Patient dataset cleaned and saved successfully!
Shape: (30000, 6)

In [27]:
# Load raw admission data
admission_clean = pd.read_csv("data/raw/admission.csv")

# 1. Standardize column names
admission_clean.columns = (
    admission_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# 2. Remove accidental whitespace from text columns
text_columns = admission_clean.select_dtypes(
    include=["object", "str"]
).columns

for column in text_columns:
    admission_clean[column] = admission_clean[column].str.strip()

# 3. Convert date columns
admission_clean["admission_date"] = pd.to_datetime(
    admission_clean["admission_date"],
    errors="coerce"
)

admission_clean["discharge_date"] = pd.to_datetime(
    admission_clean["discharge_date"],
    errors="coerce"
)

# 4. Ensure ID columns are integers
id_columns = [
    "admission_id",
    "patient_id",
    "department_id",
    "ward_id",
    "bed_id",
    "disease_id"
]

for column in id_columns:
    admission_clean[column] = admission_clean[column].astype("int64")

# 5. Create Length of Stay
admission_clean["length_of_stay"] = (
    admission_clean["discharge_date"]
    - admission_clean["admission_date"]
).dt.days

# 6. Check missing values
print("Missing values:")
print(admission_clean.isnull().sum())

# 7. Check duplicate rows
print("\nDuplicate rows:", admission_clean.duplicated().sum())

# 8. Check invalid length of stay
print(
    "Invalid length of stay:",
    (admission_clean["length_of_stay"] < 0).sum()
)

# 9. Save cleaned dataset
admission_clean.to_csv(
    "data/clean/admission_clean.csv",
    index=False
)

print("\nAdmission dataset cleaned and saved successfully!")
print("Shape:", admission_clean.shape)

print("\nLength of Stay statistics:")
print(admission_clean["length_of_stay"].describe())

Missing values:
admission_id        0
admission_date      0
discharge_date      0
admission_type      0
admission_status    0
patient_id          0
department_id       0
ward_id             0
bed_id              0
disease_id          0
length_of_stay      0
dtype: int64

Duplicate rows: 0
Invalid length of stay: 0

Admission dataset cleaned and saved successfully!
Shape: (45000, 11)

Length of Stay statistics:
count    45000.000000
mean         5.155000
std          3.271284
min          1.000000
25%          3.000000
50%          4.000000
75%          8.000000
max         15.000000
Name: length_of_stay, dtype: float64

In [28]:
# Load raw billing data
billing_clean = pd.read_csv("data/raw/billing.csv")

# 1. Standardize column names
billing_clean.columns = (
    billing_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# 2. Remove accidental whitespace from text columns
text_columns = billing_clean.select_dtypes(
    include=["object", "str"]
).columns

for column in text_columns:
    billing_clean[column] = billing_clean[column].str.strip()

# 3. Convert bill date
billing_clean["bill_date"] = pd.to_datetime(
    billing_clean["bill_date"],
    errors="coerce"
)

# 4. Ensure ID columns are integers
billing_clean["bill_id"] = billing_clean["bill_id"].astype("int64")
billing_clean["admission_id"] = billing_clean["admission_id"].astype("int64")

# 5. Ensure financial columns are numeric
amount_columns = [
    "total_amount",
    "insurance_covered_amount",
    "patient_payable_amount"
]

for column in amount_columns:
    billing_clean[column] = pd.to_numeric(
        billing_clean[column],
        errors="coerce"
    )

# 6. Check missing values
print("Missing values:")
print(billing_clean.isnull().sum())

# 7. Check duplicate rows
print("\nDuplicate rows:", billing_clean.duplicated().sum())

# 8. Check negative financial values
print("\nNegative values:")
for column in amount_columns:
    print(
        column + ":",
        (billing_clean[column] < 0).sum()
    )

# 9. Validate billing calculation
billing_clean["calculated_total"] = (
    billing_clean["insurance_covered_amount"]
    + billing_clean["patient_payable_amount"]
)

billing_clean["amount_difference"] = (
    billing_clean["total_amount"]
    - billing_clean["calculated_total"]
)

print(
    "\nBilling calculation mismatches:",
    (billing_clean["amount_difference"].abs() > 0.01).sum()
)

# 10. Remove temporary validation columns
billing_clean.drop(
    columns=["calculated_total", "amount_difference"],
    inplace=True
)

# 11. Save cleaned billing data
billing_clean.to_csv(
    "data/clean/billing_clean.csv",
    index=False
)

print("\nBilling dataset cleaned and saved successfully!")
print("Shape:", billing_clean.shape)

Missing values:
bill_id                     0
bill_date                   0
total_amount                0
insurance_covered_amount    0
patient_payable_amount      0
payment_status              0
payment_mode                0
admission_id                0
dtype: int64

Duplicate rows: 0

Negative values:
total_amount: 0
insurance_covered_amount: 0
patient_payable_amount: 0

Billing calculation mismatches: 0

Billing dataset cleaned and saved successfully!
Shape: (45000, 8)

In [29]:
# Load raw billing detail data
billing_detail_clean = pd.read_csv(
    "data/raw/billing_detail.csv"
)

# 1. Standardize column names
billing_detail_clean.columns = (
    billing_detail_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# 2. Remove accidental whitespace from text columns
text_columns = billing_detail_clean.select_dtypes(
    include=["object", "str"]
).columns

for column in text_columns:
    billing_detail_clean[column] = (
        billing_detail_clean[column].str.strip()
    )

# 3. Ensure ID columns are integers
billing_detail_clean["billing_detail_id"] = (
    billing_detail_clean["billing_detail_id"].astype("int64")
)

billing_detail_clean["bill_id"] = (
    billing_detail_clean["bill_id"].astype("int64")
)

# 4. Convert amount to numeric
billing_detail_clean["amount"] = pd.to_numeric(
    billing_detail_clean["amount"],
    errors="coerce"
)

# 5. Keep reference_id numeric
billing_detail_clean["reference_id"] = pd.to_numeric(
    billing_detail_clean["reference_id"],
    errors="coerce"
)

# 6. Check missing values
print("Missing values:")
print(billing_detail_clean.isnull().sum())

# 7. Check duplicate rows
print("\nDuplicate rows:",
      billing_detail_clean.duplicated().sum())

# 8. Check negative billing detail amounts
print("\nNegative amounts:",
      (billing_detail_clean["amount"] < 0).sum())

# 9. Verify the structural missing-value pattern
print("\nReference ID missing by charge type:")

print(
    billing_detail_clean
    .groupby("charge_type")["reference_id"]
    .apply(lambda x: x.isna().sum())
)

# 10. Save cleaned dataset
billing_detail_clean.to_csv(
    "data/clean/billing_detail_clean.csv",
    index=False
)

print("\nBilling detail dataset cleaned and saved successfully!")
print("Shape:", billing_detail_clean.shape)

Missing values:
billing_detail_id        0
charge_type              0
reference_id         67402
amount                   0
bill_id                  0
dtype: int64

Duplicate rows: 0

Negative amounts: 0

Reference ID missing by charge type:
charge_type
Drug         31344
Procedure    13575
Room             0
Test         22483
Name: reference_id, dtype: int64

Billing detail dataset cleaned and saved successfully!
Shape: (112402, 5)

In [30]:
# Supporting/reference tables to clean

supporting_files = [
    "department.csv",
    "ward.csv",
    "bed.csv",
    "disease.csv",
    "doctor.csv",
    "employee.csv",
    "drug.csv",
    "drug_inventory.csv",
    "drug_manufacturer.csv",
    "insurance_provider.csv",
    "prescription.csv",
    "patient_diagnostic.csv",
    "patient_insurance.csv",
    "diagnostic_test.csv",
    "staff_assignment.csv"
]

cleaning_summary = []

for file in supporting_files:
    
    # Load raw file
    df = pd.read_csv(os.path.join(data_path, file))
    
    # Standardize column names
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )
    
    # Strip whitespace from text columns
    text_columns = df.select_dtypes(
        include=["object", "str"]
    ).columns
    
    for column in text_columns:
        df[column] = df[column].str.strip()
    
    # Count duplicates before removing them
    duplicate_count = df.duplicated().sum()
    
    # Remove only exact duplicate rows
    if duplicate_count > 0:
        df = df.drop_duplicates()
    
    # Save cleaned file
    output_name = file.replace(".csv", "_clean.csv")
    df.to_csv(
        os.path.join(clean_path, output_name),
        index=False
    )
    
    cleaning_summary.append({
        "File": file,
        "Original Rows": len(pd.read_csv(os.path.join(data_path, file))),
        "Final Rows": len(df),
        "Columns": len(df.columns),
        "Duplicates Removed": duplicate_count,
        "Missing Values": df.isnull().sum().sum()
    })

# Display summary
supporting_summary = pd.DataFrame(cleaning_summary)

supporting_summary

,File,Original Rows,Final Rows,Columns,Duplicates Removed,Missing Values
0,department.csv,11,11,5,0,0
1,ward.csv,27,27,5,0,0
2,bed.csv,415,415,4,0,0
3,disease.csv,20,20,3,0,0
4,doctor.csv,98,98,5,0,0
5,employee.csv,500,500,7,0,0
6,drug.csv,250,250,6,0,0
7,drug_inventory.csv,250,250,6,0,0
8,drug_manufacturer.csv,300,300,5,0,0
9,insurance_provider.csv,50,50,5,0,0
10,prescription.csv,73109,73109,6,0,0
11,patient_diagnostic.csv,63269,63269,6,0,0
12,patient_insurance.csv,21617,21617,7,0,0
13,diagnostic_test.csv,9,9,5,0,0
14,staff_assignment.csv,207,207,4,0,0

In [32]:
for file in supporting_files:

    # Convert original filename to cleaned filename
    clean_file = file.replace(".csv", "_clean.csv")

    # Read cleaned file
    df = pd.read_csv(os.path.join(clean_path, clean_file))

    print("\n" + "=" * 70)
    print(clean_file)
    print("=" * 70)
    print(list(df.columns))

======================================================================
department_clean.csv
======================================================================
['department_id', 'department_name', 'department_type', 'floor_number', 'status']

======================================================================
ward_clean.csv
======================================================================
['ward_id', 'ward_name', 'ward_type', 'total_beds', 'department_id']

======================================================================
bed_clean.csv
======================================================================
['bed_id', 'bed_number', 'bed_status', 'ward_id']

======================================================================
disease_clean.csv
======================================================================
['disease_id', 'disease_name', 'disease_category']

======================================================================
doctor_clean.csv
======================================================================
['doctor_id', 'employee_id', 'specialization', 'qualification', 'experience_years']

======================================================================
employee_clean.csv
======================================================================
['employee_id', 'employee_name', 'gender', 'role', 'employment_type', 'date_of_joining', 'department_id']

======================================================================
drug_clean.csv
======================================================================
['drug_id', 'drug_name', 'brand_name', 'drug_category', 'unit_cost', 'manufacturer_id']

======================================================================
drug_inventory_clean.csv
======================================================================
['inventory_id', 'current_stock', 'reorder_level', 'inventory_status', 'last_restock_date', 'drug_id']

======================================================================
drug_manufacturer_clean.csv
======================================================================
['manufacturer_id', 'manufacturer_name', 'country', 'reliability_rating', 'contract_status']

======================================================================
insurance_provider_clean.csv
======================================================================
['insurance_provider_id', 'provider_name', 'provider_type', 'contact_details', 'coverage_limit']

======================================================================
prescription_clean.csv
======================================================================
['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']

======================================================================
patient_diagnostic_clean.csv
======================================================================
['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']

======================================================================
patient_insurance_clean.csv
======================================================================
['patient_insurance_id', 'policy_number', 'coverage_percentage', 'policy_start_date', 'policy_end_date', 'patient_id', 'insurance_provider_id']

======================================================================
diagnostic_test_clean.csv
======================================================================
['test_id', 'test_name', 'test_category', 'standard_cost', 'department_id']

======================================================================
staff_assignment_clean.csv
======================================================================
['assignment_id', 'employee_id', 'ward_id', 'shift']

In [33]:
# Load cleaned datasets

patient = pd.read_csv(
    "data/clean/patient_clean.csv",
    parse_dates=["date_of_birth"]
)

admission = pd.read_csv(
    "data/clean/admission_clean.csv",
    parse_dates=["admission_date", "discharge_date"]
)

department = pd.read_csv(
    "data/clean/department_clean.csv"
)

ward = pd.read_csv(
    "data/clean/ward_clean.csv"
)

bed = pd.read_csv(
    "data/clean/bed_clean.csv"
)

disease = pd.read_csv(
    "data/clean/disease_clean.csv"
)

print("All datasets loaded successfully!")

print("\nShapes:")
print("Patient:", patient.shape)
print("Admission:", admission.shape)
print("Department:", department.shape)
print("Ward:", ward.shape)
print("Bed:", bed.shape)
print("Disease:", disease.shape)

All datasets loaded successfully!

Shapes:
Patient: (30000, 6)
Admission: (45000, 11)
Department: (11, 5)
Ward: (27, 5)
Bed: (415, 4)
Disease: (20, 3)

In [34]:
hospital_operations = admission.merge(
    patient[
        [
            "patient_id",
            "gender",
            "date_of_birth",
            "blood_group",
            "city"
        ]
    ],
    on="patient_id",
    how="left",
    validate="many_to_one"
)

print("After Patient merge:")
print(hospital_operations.shape)

print("\nMissing patient information:")
print(
    hospital_operations[
        ["gender", "date_of_birth", "blood_group", "city"]
    ].isnull().sum()
)

After Patient merge:
(45000, 15)

Missing patient information:
gender           0
date_of_birth    0
blood_group      0
city             0
dtype: int64

In [35]:
hospital_operations = hospital_operations.merge(
    department[
        [
            "department_id",
            "department_name",
            "department_type",
            "floor_number"
        ]
    ],
    on="department_id",
    how="left",
    validate="many_to_one"
)

print("After Department merge:")
print(hospital_operations.shape)

print("\nMissing department information:")
print(
    hospital_operations[
        [
            "department_name",
            "department_type",
            "floor_number"
        ]
    ].isnull().sum()
)

After Department merge:
(45000, 18)

Missing department information:
department_name    0
department_type    0
floor_number       0
dtype: int64

In [36]:
hospital_operations = hospital_operations.merge(
    ward[
        [
            "ward_id",
            "ward_name",
            "ward_type",
            "total_beds"
        ]
    ],
    on="ward_id",
    how="left",
    validate="many_to_one"
)

print("After Ward merge:")
print(hospital_operations.shape)

print("\nMissing ward information:")
print(
    hospital_operations[
        [
            "ward_name",
            "ward_type",
            "total_beds"
        ]
    ].isnull().sum()
)

After Ward merge:
(45000, 21)

Missing ward information:
ward_name     0
ward_type     0
total_beds    0
dtype: int64

In [37]:
hospital_operations = hospital_operations.merge(
    bed[
        [
            "bed_id",
            "bed_number",
            "bed_status"
        ]
    ],
    on="bed_id",
    how="left",
    validate="many_to_one"
)

print("After Bed merge:")
print(hospital_operations.shape)

print("\nMissing bed information:")
print(
    hospital_operations[
        [
            "bed_number",
            "bed_status"
        ]
    ].isnull().sum()
)

After Bed merge:
(45000, 23)

Missing bed information:
bed_number    0
bed_status    0
dtype: int64

In [38]:
hospital_operations = hospital_operations.merge(
    disease[
        [
            "disease_id",
            "disease_name",
            "disease_category"
        ]
    ],
    on="disease_id",
    how="left",
    validate="many_to_one"
)

print("After Disease merge:")
print(hospital_operations.shape)

print("\nMissing disease information:")
print(
    hospital_operations[
        [
            "disease_name",
            "disease_category"
        ]
    ].isnull().sum()
)

After Disease merge:
(45000, 25)

Missing disease information:
disease_name        0
disease_category    0
dtype: int64

In [39]:
print("FINAL HOSPITAL OPERATIONS DATASET")
print("=" * 50)

print("Rows:", len(hospital_operations))
print("Columns:", len(hospital_operations.columns))

print("\nDuplicate rows:",
      hospital_operations.duplicated().sum())

print("\nUnique admission IDs:",
      hospital_operations["admission_id"].nunique())

print("\nMissing values:")
print(hospital_operations.isnull().sum())

FINAL HOSPITAL OPERATIONS DATASET
==================================================
Rows: 45000
Columns: 25

Duplicate rows: 0

Unique admission IDs: 45000

Missing values:
admission_id        0
admission_date      0
discharge_date      0
admission_type      0
admission_status    0
patient_id          0
department_id       0
ward_id             0
bed_id              0
disease_id          0
length_of_stay      0
gender              0
date_of_birth       0
blood_group         0
city                0
department_name     0
department_type     0
floor_number        0
ward_name           0
ward_type           0
total_beds          0
bed_number          0
bed_status          0
disease_name        0
disease_category    0
dtype: int64

In [40]:
# Save Hospital Operations analytical dataset

hospital_operations.to_csv(
    "data/clean/hospital_operations.csv",
    index=False
)

print("Hospital Operations dataset saved successfully!")
print("File: data/clean/hospital_operations.csv")
print("Rows:", hospital_operations.shape[0])
print("Columns:", hospital_operations.shape[1])

Hospital Operations dataset saved successfully!
File: data/clean/hospital_operations.csv
Rows: 45000
Columns: 25

In [41]:
# ==========================================
# HOSPITAL OPERATIONS - KEY PERFORMANCE INDICATORS
# ==========================================

total_admissions = hospital_operations["admission_id"].nunique()

total_patients = hospital_operations["patient_id"].nunique()

average_length_of_stay = hospital_operations["length_of_stay"].mean()

total_beds = bed["bed_id"].nunique()

occupied_beds = (
    bed["bed_status"] == "Occupied"
).sum()

available_beds = (
    bed["bed_status"] == "Available"
).sum()

bed_occupancy_rate = (
    occupied_beds / total_beds
) * 100


print("========== HOSPITAL OPERATIONS KPIs ==========")

print("Total Admissions:", total_admissions)
print("Unique Patients:", total_patients)
print(
    "Average Length of Stay:",
    round(average_length_of_stay, 2),
    "days"
)

print("Total Beds:", total_beds)
print("Occupied Beds:", occupied_beds)
print("Available Beds:", available_beds)
print(
    "Current Bed Occupancy Rate:",
    round(bed_occupancy_rate, 2),
    "%"
)

========== HOSPITAL OPERATIONS KPIs ==========
Total Admissions: 45000
Unique Patients: 23275
Average Length of Stay: 5.16 days
Total Beds: 415
Occupied Beds: 270
Available Beds: 145
Current Bed Occupancy Rate: 65.06 %

In [42]:
# Load cleaned prescription data

prescription = pd.read_csv(
    "data/clean/prescription_clean.csv"
)

print("Prescription shape:", prescription.shape)
print("\nColumns:")
print(prescription.columns.tolist())

print("\nUnique admissions:")
print(prescription["admission_id"].nunique())

Prescription shape: (73109, 6)

Columns:
['prescription_id', 'dosage', 'frequency', 'duration_days', 'admission_id', 'drug_id']

Unique admissions:
29287

In [43]:
# Aggregate prescriptions to admission level

prescription_summary = (
    prescription
    .groupby("admission_id")
    .agg(
        number_of_prescriptions=(
            "prescription_id",
            "count"
        ),
        unique_drugs=(
            "drug_id",
            "nunique"
        ),
        total_prescription_days=(
            "duration_days",
            "sum"
        ),
        average_prescription_duration=(
            "duration_days",
            "mean"
        )
    )
    .reset_index()
)

# Round average duration
prescription_summary["average_prescription_duration"] = (
    prescription_summary["average_prescription_duration"]
    .round(2)
)

print("Prescription summary shape:")
print(prescription_summary.shape)

print("\nSample:")
print(prescription_summary.head())

Prescription summary shape:
(29287, 5)

Sample:
   admission_id  number_of_prescriptions  unique_drugs  \
0             1                        4             4
1             3                        4             4
2             4                        2             2
3             7                        3             3
4             8                        3             3

   total_prescription_days  average_prescription_duration
0                       35                           8.75
1                       30                           7.50
2                       21                          10.50
3                       12                           4.00
4                       35                          11.67

In [44]:
print(
    "Unique admission IDs:",
    prescription_summary["admission_id"].nunique()
)

print(
    "Duplicate admission IDs:",
    prescription_summary["admission_id"].duplicated().sum()
)

print(
    "Missing admission IDs:",
    prescription_summary["admission_id"].isna().sum()
)

Unique admission IDs: 29287
Duplicate admission IDs: 0
Missing admission IDs: 0

In [45]:
# Load cleaned patient diagnostic data

patient_diagnostic = pd.read_csv(
    "data/clean/patient_diagnostic_clean.csv"
)

print("Patient Diagnostic shape:", patient_diagnostic.shape)

print("\nColumns:")
print(patient_diagnostic.columns.tolist())

print(
    "\nUnique admissions:",
    patient_diagnostic["admission_id"].nunique()
)

Patient Diagnostic shape: (63269, 6)

Columns:
['patient_diagnostic_id', 'test_date', 'result_status', 'admission_id', 'test_id', 'doctor_id']

Unique admissions: 31512

In [46]:
# Aggregate diagnostic records to admission level

diagnostic_summary = (
    patient_diagnostic
    .groupby("admission_id")
    .agg(
        number_of_diagnostic_tests=(
            "patient_diagnostic_id",
            "count"
        ),
        unique_tests=(
            "test_id",
            "nunique"
        ),
        unique_doctors=(
            "doctor_id",
            "nunique"
        )
    )
    .reset_index()
)

print("Diagnostic summary shape:")
print(diagnostic_summary.shape)

print("\nSample:")
print(diagnostic_summary.head())

Diagnostic summary shape:
(31512, 4)

Sample:
   admission_id  number_of_diagnostic_tests  unique_tests  unique_doctors
0             1                           3             3               3
1             2                           1             1               1
2             3                           2             2               2
3             4                           3             3               3
4             5                           3             3               3

In [47]:
print(
    "Unique admission IDs:",
    diagnostic_summary["admission_id"].nunique()
)

print(
    "Duplicate admission IDs:",
    diagnostic_summary["admission_id"].duplicated().sum()
)

print(
    "Missing admission IDs:",
    diagnostic_summary["admission_id"].isna().sum()
)

Unique admission IDs: 31512
Duplicate admission IDs: 0
Missing admission IDs: 0

In [48]:
# Load cleaned billing detail data

billing_detail = pd.read_csv(
    "data/clean/billing_detail_clean.csv"
)

print("Billing detail shape:", billing_detail.shape)

print("\nColumns:")
print(billing_detail.columns.tolist())

print("\nCharge types:")
print(billing_detail["charge_type"].value_counts())

Billing detail shape: (112402, 5)

Columns:
['billing_detail_id', 'charge_type', 'reference_id', 'amount', 'bill_id']

Charge types:
charge_type
Room         45000
Drug         31344
Test         22483
Procedure    13575
Name: count, dtype: int64

In [49]:
# Create billing-detail summary by bill

billing_detail_summary = (
    billing_detail
    .pivot_table(
        index="bill_id",
        columns="charge_type",
        values="amount",
        aggfunc="sum",
        fill_value=0
    )
    .reset_index()
)

# Rename charge columns
billing_detail_summary = billing_detail_summary.rename(
    columns={
        "Room": "room_charges",
        "Drug": "drug_charges",
        "Test": "test_charges",
        "Procedure": "procedure_charges"
    }
)

print("Billing detail summary shape:")
print(billing_detail_summary.shape)

print("\nColumns:")
print(billing_detail_summary.columns.tolist())

print("\nSample:")
print(billing_detail_summary.head())

Billing detail summary shape:
(45000, 5)

Columns:
['bill_id', 'drug_charges', 'procedure_charges', 'room_charges', 'test_charges']

Sample:
charge_type  bill_id  drug_charges  procedure_charges  room_charges  \
0                  1          1844                  0          4884
1                  2          2489               6205         70010
2                  3           615                  0         40230
3                  4             0                  0         10445
4                  5             0                  0         23355

charge_type  test_charges
0                       0
1                     562
2                    1726
3                       0
4                       0

In [50]:
print(
    "Unique bill IDs:",
    billing_detail_summary["bill_id"].nunique()
)

print(
    "Duplicate bill IDs:",
    billing_detail_summary["bill_id"].duplicated().sum()
)

print(
    "Missing bill IDs:",
    billing_detail_summary["bill_id"].isna().sum()
)

Unique bill IDs: 45000
Duplicate bill IDs: 0
Missing bill IDs: 0

In [51]:
# Connect billing details to admissions

billing_with_details = billing.merge(
    billing_detail_summary,
    on="bill_id",
    how="left",
    validate="one_to_one"
)

print("Billing + Billing Detail shape:")
print(billing_with_details.shape)

print("\nUnique bill IDs:",
      billing_with_details["bill_id"].nunique())

print("\nDuplicate bill IDs:",
      billing_with_details["bill_id"].duplicated().sum())

Billing + Billing Detail shape:
(45000, 14)

Unique bill IDs: 45000

Duplicate bill IDs: 0

In [52]:
charge_columns = [
    "room_charges",
    "drug_charges",
    "test_charges",
    "procedure_charges"
]

print(
    billing_with_details[charge_columns].isnull().sum()
)

room_charges         0
drug_charges         0
test_charges         0
procedure_charges    0
dtype: int64

In [53]:
billing_with_details[charge_columns] = (
    billing_with_details[charge_columns]
    .fillna(0)
)

In [54]:
print(
    billing_with_details[charge_columns].isnull().sum()
)

room_charges         0
drug_charges         0
test_charges         0
procedure_charges    0
dtype: int64

In [55]:
billing_with_details["calculated_charge_total"] = (
    billing_with_details["room_charges"]
    + billing_with_details["drug_charges"]
    + billing_with_details["test_charges"]
    + billing_with_details["procedure_charges"]
)

billing_with_details["charge_difference"] = (
    billing_with_details["total_amount"]
    - billing_with_details["calculated_charge_total"]
)

print(
    "Bills where charge total differs from bill total:",
    (
        billing_with_details["charge_difference"].abs() > 0.01
    ).sum()
)

print(
    "Largest difference:",
    billing_with_details["charge_difference"].abs().max()
)

Bills where charge total differs from bill total: 44998
Largest difference: 129152

In [56]:
billing_with_details = billing_with_details.drop(
    columns=["calculated_charge_total", "charge_difference"]
)

print(billing_with_details.shape)

(45000, 14)

In [57]:
print("Unique admissions in billing:",
      billing_with_details["admission_id"].nunique())

print("Duplicate admission IDs:",
      billing_with_details["admission_id"].duplicated().sum())

print("Missing admission IDs:",
      billing_with_details["admission_id"].isna().sum())

Unique admissions in billing: 45000
Duplicate admission IDs: 0
Missing admission IDs: 0

In [58]:
# Select billing columns for the final dataset

billing_final = billing_with_details[
    [
        "admission_id",
        "total_amount",
        "insurance_covered_amount",
        "patient_payable_amount",
        "payment_status",
        "payment_mode",
        "room_charges",
        "drug_charges",
        "test_charges",
        "procedure_charges"
    ]
].copy()

print("Billing final shape:", billing_final.shape)

Billing final shape: (45000, 10)

In [59]:
# Merge billing information into hospital operations dataset

final_dataset = hospital_operations.merge(
    billing_final,
    on="admission_id",
    how="left",
    validate="one_to_one"
)

print("After billing merge:")
print("Rows:", final_dataset.shape[0])
print("Columns:", final_dataset.shape[1])

After billing merge:
Rows: 45000
Columns: 34

In [60]:
final_dataset = final_dataset.merge(
    prescription_summary,
    on="admission_id",
    how="left",
    validate="one_to_one"
)

print("After prescription merge:")
print("Rows:", final_dataset.shape[0])
print("Columns:", final_dataset.shape[1])

After prescription merge:
Rows: 45000
Columns: 38

In [61]:
final_dataset = final_dataset.merge(
    diagnostic_summary,
    on="admission_id",
    how="left",
    validate="one_to_one"
)

print("After diagnostic merge:")
print("Rows:", final_dataset.shape[0])
print("Columns:", final_dataset.shape[1])

After diagnostic merge:
Rows: 45000
Columns: 41

In [62]:
print("Prescription/Diagnostic missing values:")
print(
    final_dataset[
        [
            "number_of_prescriptions",
            "unique_drugs",
            "total_prescription_days",
            "average_prescription_duration",
            "number_of_diagnostic_tests",
            "unique_tests",
            "unique_doctors"
        ]
    ].isnull().sum()
)

Prescription/Diagnostic missing values:
number_of_prescriptions          15713
unique_drugs                     15713
total_prescription_days          15713
average_prescription_duration    15713
number_of_diagnostic_tests       13488
unique_tests                     13488
unique_doctors                   13488
dtype: int64

In [63]:
count_columns = [
    "number_of_prescriptions",
    "unique_drugs",
    "total_prescription_days",
    "number_of_diagnostic_tests",
    "unique_tests",
    "unique_doctors"
]

final_dataset[count_columns] = (
    final_dataset[count_columns]
    .fillna(0)
)

In [64]:
print("=" * 60)
print("FINAL DATASET VALIDATION")
print("=" * 60)

print("Rows:", len(final_dataset))

print(
    "Unique admission IDs:",
    final_dataset["admission_id"].nunique()
)

print(
    "Duplicate admission IDs:",
    final_dataset["admission_id"].duplicated().sum()
)

print(
    "Duplicate complete rows:",
    final_dataset.duplicated().sum()
)

print("\nShape:")
print(final_dataset.shape)

============================================================
FINAL DATASET VALIDATION
============================================================
Rows: 45000
Unique admission IDs: 45000
Duplicate admission IDs: 0
Duplicate complete rows: 0

Shape:
(45000, 41)

In [65]:
# Save the final integrated cleaned dataset

final_dataset.to_csv(
    "data/clean/Hospital_Operations_Patient_Analytics_Clean.csv",
    index=False
)

print("Final cleaned dataset saved successfully!")
print("File: data/clean/Hospital_Operations_Patient_Analytics_Clean.csv")
print("Rows:", final_dataset.shape[0])
print("Columns:", final_dataset.shape[1])

Final cleaned dataset saved successfully!
File: data/clean/Hospital_Operations_Patient_Analytics_Clean.csv
Rows: 45000
Columns: 41

In [66]:
# Final file verification

final_check = pd.read_csv(
    "data/clean/Hospital_Operations_Patient_Analytics_Clean.csv"
)

print("File loaded successfully!")
print("Shape:", final_check.shape)
print("Unique admission IDs:",
      final_check["admission_id"].nunique())
print("Duplicate rows:",
      final_check.duplicated().sum())

File loaded successfully!
Shape: (45000, 41)
Unique admission IDs: 45000
Duplicate rows: 0

In [3]:
import pandas as pd

final_dataset = pd.read_csv(
    "data/clean/Hospital_Operations_Patient_Analytics_Clean.csv"
)

print("Dataset loaded successfully!")
print("Shape:", final_dataset.shape)

Dataset loaded successfully!
Shape: (45000, 41)

In [4]:
final_dataset.isnull().sum()

admission_id                         0
admission_date                       0
discharge_date                       0
admission_type                       0
admission_status                     0
patient_id                           0
department_id                        0
ward_id                              0
bed_id                               0
disease_id                           0
length_of_stay                       0
gender                               0
date_of_birth                        0
blood_group                          0
city                                 0
department_name                      0
department_type                      0
floor_number                         0
ward_name                            0
ward_type                            0
total_beds                           0
bed_number                           0
bed_status                           0
disease_name                         0
disease_category                     0
total_amount                         0
insurance_covered_amount             0
patient_payable_amount               0
payment_status                       0
payment_mode                         0
room_charges                         0
drug_charges                         0
test_charges                         0
procedure_charges                    0
number_of_prescriptions              0
unique_drugs                         0
total_prescription_days              0
average_prescription_duration    15713
number_of_diagnostic_tests           0
unique_tests                         0
unique_doctors                       0
dtype: int64

In [5]:
final_dataset[final_dataset["average_prescription_duration"].isna()][
    ["admission_id", "number_of_prescriptions", "total_prescription_days",
     "average_prescription_duration"]
].head(20)

,admission_id,number_of_prescriptions,total_prescription_days,average_prescription_duration
1,2,0.0,0.0,NaN
4,5,0.0,0.0,NaN
5,6,0.0,0.0,NaN
10,11,0.0,0.0,NaN
11,12,0.0,0.0,NaN
13,14,0.0,0.0,NaN
17,18,0.0,0.0,NaN
18,19,0.0,0.0,NaN
21,22,0.0,0.0,NaN
25,26,0.0,0.0,NaN
29,30,0.0,0.0,NaN
30,31,0.0,0.0,NaN
31,32,0.0,0.0,NaN
35,36,0.0,0.0,NaN
41,42,0.0,0.0,NaN
51,52,0.0,0.0,NaN
52,53,0.0,0.0,NaN
60,61,0.0,0.0,NaN
62,63,0.0,0.0,NaN
67,68,0.0,0.0,NaN

In [6]:
print(
    "Missing average duration where prescriptions = 0:",
    (
        final_dataset["average_prescription_duration"].isna()
        & (final_dataset["number_of_prescriptions"] == 0)
    ).sum()
)

Missing average duration where prescriptions = 0: 15713

In [7]:
final_dataset["average_prescription_duration"] = (
    final_dataset["average_prescription_duration"].fillna(0)
)

In [8]:
print("Missing values after cleaning:")
print(final_dataset.isnull().sum())

print("\nTotal missing values:",
      final_dataset.isnull().sum().sum())

Missing values after cleaning:
admission_id                     0
admission_date                   0
discharge_date                   0
admission_type                   0
admission_status                 0
patient_id                       0
department_id                    0
ward_id                          0
bed_id                           0
disease_id                       0
length_of_stay                   0
gender                           0
date_of_birth                    0
blood_group                      0
city                             0
department_name                  0
department_type                  0
floor_number                     0
ward_name                        0
ward_type                        0
total_beds                       0
bed_number                       0
bed_status                       0
disease_name                     0
disease_category                 0
total_amount                     0
insurance_covered_amount         0
patient_payable_amount           0
payment_status                   0
payment_mode                     0
room_charges                     0
drug_charges                     0
test_charges                     0
procedure_charges                0
number_of_prescriptions          0
unique_drugs                     0
total_prescription_days          0
average_prescription_duration    0
number_of_diagnostic_tests       0
unique_tests                     0
unique_doctors                   0
dtype: int64

Total missing values: 0

In [9]:
final_dataset.to_csv(
    "data/clean/Hospital_Operations_Patient_Analytics_Clean.csv",
    index=False
)

print("Final cleaned dataset saved successfully!")
print("Shape:", final_dataset.shape)

Final cleaned dataset saved successfully!
Shape: (45000, 41)