In [372]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [373]:

df = pd.read_csv("dummy_hospital_generated.csv")
df.head(500)

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,...,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
0,01-02-2025,123517868,2002,Pakistan,F,ABC123,Dr. Shawn Martin,Consultant,Inactive,1.048,...,PureWin Insurance,Premium,Insurance,OP,0,1,Medical,07:00:00,Yes,548
1,01-10-2025,123810649,1981,Indonesia,F,VBN123,Dr. Peter Novak,Consultant,Active,0.942,...,PureWin Insurance,Basic,Insurance,OP,0,2,Medical,NaN,NaN,1198
2,01-08-2025,123979661,1990,Egypt,M,FGH123,Dr. Sofia Kim,GP,Active,1.089,...,PureWin Insurance,Premium,Insurance,OP,0,1,Medical,NaN,NaN,586
3,01-06-2025,123927914,1991,Germany,M,HJK123,Dr. Priya Iyer,Specialist,Active,0.970,...,BlueMedic Charity,NaN,Corporate,IP,5,1,Medical,09:13:00,Yes,28717
4,01-06-2025,123605097,2000,UAE,F,ABC234,Dr. Thomas Muller,Specialist,Active,1.006,...,Nextcare Insurance,NC-Blue,Insurance,IP,4,3,Medical,13:39:00,No,117129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,01-05-2025,123796550,1985,USA,F,FGH234,Dr. Hana Suzuki,Consultant,Inactive,0.989,...,BlueMedic Charity,NaN,Corporate,OP,0,1,Surgery,09:07:00,Yes,907
496,01-02-2025,123742348,2000,Netherlands,M,VBN123,Dr. Peter Novak,Consultant,Active,0.920,...,Nextcare Insurance,NC-Gold,Insurance,OP,0,1,Medical,NaN,NaN,1685
497,01-05-2025,123652197,1963,India,M,DEF232,Dr. Lily James,Specialist,Active,1.037,...,Nextcare Insurance,NC-Blue,Insurance,OP,0,1,Surgery,NaN,NaN,1552
498,01-12-2025,123979202,1980,Bangladesh,F,FGH123,Dr. Sofia Kim,GP,Active,1.253,...,TotalHealth Insurance,TH-Plus,Insurance,OP,0,3,Surgery,NaN,NaN,2013
499,01-06-2025,123734929,1971,USA,M,ABC123,Dr. Shawn Martin,Consultant,Inactive,1.151,...,PureWin Insurance,Advance,Insurance,OP,0,2,Surgery,NaN,NaN,1533

In [374]:
data = df.copy()

In [375]:
data.shape

(500, 21)

In [376]:
data.columns

Index(['Month', 'Case_No', 'DOB', 'Nationality', 'Gender', 'DoctorLicense',
       'DoctorName', 'Doctor Type', 'Doctor Status', 'CMI Value', 'Specialty',
       'Insurance/Payer', 'InsurancePlanName', 'Payer Mix', 'Case type', 'LOS',
       'Severity', 'Surgical Mix', 'Discharge Time', 'Discharge Before 12PM',
       'Revenue'],
      dtype='object')

In [377]:
data.dtypes

Month                     object
Case_No                    int64
DOB                        int64
Nationality               object
Gender                    object
DoctorLicense             object
DoctorName                object
Doctor Type               object
Doctor Status             object
CMI Value                float64
Specialty                 object
Insurance/Payer           object
InsurancePlanName         object
Payer Mix                 object
Case type                 object
LOS                        int64
Severity                   int64
Surgical Mix              object
Discharge Time            object
Discharge Before 12PM     object
Revenue                    int64
dtype: object

In [378]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Month                  500 non-null    object
 1   Case_No                500 non-null    int64
 2   DOB                    500 non-null    int64
 3   Nationality            500 non-null    object
 4   Gender                 500 non-null    object
 5   DoctorLicense          500 non-null    object
 6   DoctorName             500 non-null    object
 7   Doctor Type            500 non-null    object
 8   Doctor Status          500 non-null    object
 9   CMI Value              500 non-null    float64
 10  Specialty              500 non-null    object
 11  Insurance/Payer        500 non-null    object
 12  InsurancePlanName      428 non-null    object
 13  Payer Mix              500 non-null    object
 14  Case type              500 non-null    object
 15  LOS                    500 non-null    int64
 16  Severity               500 non-null    int64
 17  Surgical Mix           500 non-null    object
 18  Discharge Time         262 non-null    object
 19  Discharge Before 12PM  262 non-null    object
 20  Revenue                500 non-null    int64
dtypes: float64(1), int64(5), object(15)
memory usage: 82.2+ KB

In [379]:
data.isnull().sum()

Month                      0
Case_No                    0
DOB                        0
Nationality                0
Gender                     0
DoctorLicense              0
DoctorName                 0
Doctor Type                0
Doctor Status              0
CMI Value                  0
Specialty                  0
Insurance/Payer            0
InsurancePlanName         72
Payer Mix                  0
Case type                  0
LOS                        0
Severity                   0
Surgical Mix               0
Discharge Time           238
Discharge Before 12PM    238
Revenue                    0
dtype: int64

In [380]:
missing_percentage = (data.isnull().sum() / len(data)) * 100

missing_percentage.sort_values(ascending=False)

Discharge Before 12PM    47.6
Discharge Time           47.6
InsurancePlanName        14.4
Month                     0.0
Insurance/Payer           0.0
Surgical Mix              0.0
Severity                  0.0
LOS                       0.0
Case type                 0.0
Payer Mix                 0.0
Specialty                 0.0
Case_No                   0.0
CMI Value                 0.0
Doctor Status             0.0
Doctor Type               0.0
DoctorName                0.0
DoctorLicense             0.0
Gender                    0.0
Nationality               0.0
DOB                       0.0
Revenue                   0.0
dtype: float64

In [381]:
final_missing = (data.isnull().sum() / len(data)) * 100

final_missing[final_missing > 0]

InsurancePlanName        14.4
Discharge Time           47.6
Discharge Before 12PM    47.6
dtype: float64

In [382]:
missing_table = pd.DataFrame({
    "Missing Values": data.isnull().sum(),
    "Missing Percentage": (data.isnull().sum() / len(data)) * 100
})

missing_table = missing_table.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing_table

                       Missing Values  Missing Percentage
Discharge Before 12PM             238                47.6
Discharge Time                    238                47.6
InsurancePlanName                  72                14.4
Month                               0                 0.0
Insurance/Payer                     0                 0.0
Surgical Mix                        0                 0.0
Severity                            0                 0.0
LOS                                 0                 0.0
Case type                           0                 0.0
Payer Mix                           0                 0.0
Specialty                           0                 0.0
Case_No                             0                 0.0
CMI Value                           0                 0.0
Doctor Status                       0                 0.0
Doctor Type                         0                 0.0
DoctorName                          0                 0.0
DoctorLicense                       0                 0.0
Gender                              0                 0.0
Nationality                         0                 0.0
DOB                                 0                 0.0
Revenue                             0                 0.0

In [383]:
data.duplicated().sum()

0

In [384]:
data.describe()

,Case_No,DOB,CMI Value,LOS,Severity,Revenue
count,5.000000e+02,500.000000,500.000000,500.000,500.000000,500.00000
mean,1.237317e+08,1984.408000,1.037098,1.284,1.782000,17046.72800
std,1.585829e+05,14.024225,0.110963,1.946,0.712384,30527.29352
min,1.234584e+08,1955.000000,0.710000,0.000,1.000000,99.00000
25%,1.235896e+08,1975.000000,0.960000,0.000,1.000000,830.00000
50%,1.237408e+08,1987.000000,1.035000,0.000,2.000000,1628.50000
75%,1.238734e+08,1996.000000,1.110250,3.000,2.000000,15310.50000
max,1.239995e+08,2005.000000,1.394000,7.000,3.000000,160962.00000

In [385]:
data.describe(include="object")

,Month,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,Specialty,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,Surgical Mix,Discharge Time,Discharge Before 12PM
count,500,500,500,500,500,500,500,500,500,428,500,500,500,262,262
unique,12,14,2,10,10,3,2,10,6,9,2,3,2,228,2
top,01-02-2025,India,M,FGH234,Dr. Hana Suzuki,Specialist,Active,General Surgery,PureWin Insurance,Advance,Insurance,OP,Medical,07:00:00,No
freq,56,101,290,70,70,236,405,70,211,84,428,308,300,2,141

In [386]:
#DATA TRANSFORMATION

data["DOB"] = pd.to_numeric(data["DOB"], errors="coerce")

data["DOB"] = pd.to_datetime(
    data["DOB"].astype("Int64").astype(str),
    format="%Y",
    errors="coerce"
)

In [387]:
data["DOB"].head(10)

0   2002-01-01
1   1981-01-01
2   1990-01-01
3   1991-01-01
4   2000-01-01
5   1983-01-01
6   1991-01-01
7   1983-01-01
8   2000-01-01
9   1958-01-01
Name: DOB, dtype: datetime64[ns]

In [388]:
current_year = pd.Timestamp.today().year

data["Age"] = current_year - data["DOB"].dt.year

In [389]:
data[["DOB", "Age"]].head(10)

         DOB  Age
0 2002-01-01   24
1 1981-01-01   45
2 1990-01-01   36
3 1991-01-01   35
4 2000-01-01   26
5 1983-01-01   43
6 1991-01-01   35
7 1983-01-01   43
8 2000-01-01   26
9 1958-01-01   68

In [390]:
bins = [0, 18, 30, 45, 60, 75, 120]

labels = ["0-18", "19-30", "31-45", "46-60", "61-75", "76+"]

data["Age Group"] = pd.cut(
    data["Age"],
    bins=bins,
    labels=labels,
    right=True
)

In [391]:
data[["Age", "Age Group"]].head(10)

   Age Age Group
0   24     19-30
1   45     31-45
2   36     31-45
3   35     31-45
4   26     19-30
5   43     31-45
6   35     31-45
7   43     31-45
8   26     19-30
9   68     61-75

In [392]:
data["Age Group"].value_counts().sort_index()

Age Group
0-18       0
19-30    129
31-45    206
46-60     90
61-75     75
76+        0
Name: count, dtype: int64

In [393]:
data[["Age", "CMI Value", "LOS", "Revenue"]].describe()

              Age   CMI Value      LOS       Revenue
count  500.000000  500.000000  500.000     500.00000
mean    41.592000    1.037098    1.284   17046.72800
std     14.024225    0.110963    1.946   30527.29352
min     21.000000    0.710000    0.000      99.00000
25%     30.000000    0.960000    0.000     830.00000
50%     39.000000    1.035000    0.000    1628.50000
75%     51.000000    1.110250    3.000   15310.50000
max     71.000000    1.394000    7.000  160962.00000

In [394]:
data[(data["Age"] < 0) | (data["Age"] > 120)]

Empty DataFrame
Columns: [Month, Case_No, DOB, Nationality, Gender, DoctorLicense, DoctorName, Doctor Type, Doctor Status, CMI Value, Specialty, Insurance/Payer, InsurancePlanName, Payer Mix, Case type, LOS, Severity, Surgical Mix, Discharge Time, Discharge Before 12PM, Revenue, Age, Age Group]
Index: []

[0 rows x 23 columns]

In [395]:
data[data["LOS"] < 0]
data[data["CMI Value"] < 0]
data[data["Revenue"] < 0]

Empty DataFrame
Columns: [Month, Case_No, DOB, Nationality, Gender, DoctorLicense, DoctorName, Doctor Type, Doctor Status, CMI Value, Specialty, Insurance/Payer, InsurancePlanName, Payer Mix, Case type, LOS, Severity, Surgical Mix, Discharge Time, Discharge Before 12PM, Revenue, Age, Age Group]
Index: []

[0 rows x 23 columns]

In [396]:
categorical_columns = [
    "Gender",
    "Doctor Type",
    "Doctor Status",
    "Specialty",
    "Insurance/Payer",
    "Payer Mix",
    "Case type",
    "Severity",
    "Surgical Mix"
]

for column in categorical_columns:
    data[column] = data[column].astype("string").str.strip().str.title()

In [397]:
data[categorical_columns].head()

,Gender,Doctor Type,Doctor Status,Specialty,Insurance/Payer,Payer Mix,Case type,Severity,Surgical Mix
0,F,Consultant,Inactive,Emergency,Purewin Insurance,Insurance,Op,1,Medical
1,F,Consultant,Active,Orthopaedics,Purewin Insurance,Insurance,Op,2,Medical
2,M,Gp,Active,Internal Medicine,Purewin Insurance,Insurance,Op,1,Medical
3,M,Specialist,Active,Obstetrics & Gynecology,Bluemedic Charity,Corporate,Ip,1,Medical
4,F,Specialist,Active,Nephrology,Nextcare Insurance,Insurance,Ip,3,Medical

In [398]:
data["Gender"].value_counts()

Gender
M    290
F    210
Name: count, dtype: Int64

In [399]:
data["Severity"].value_counts()

Severity
2    223
1    193
3     84
Name: count, dtype: Int64

In [400]:
data["Discharge Time"] = pd.to_datetime(
    data["Discharge Time"],
    format="%H:%M:%S",
    errors="coerce"
)

In [401]:
data["Discharge Hour"] = data["Discharge Time"].dt.hour

In [402]:
data[["Discharge Time", "Discharge Hour"]].head(10)

       Discharge Time  Discharge Hour
0 1900-01-01 07:00:00             7.0
1                 NaT             NaN
2                 NaT             NaN
3 1900-01-01 09:13:00             9.0
4 1900-01-01 13:39:00            13.0
5                 NaT             NaN
6                 NaT             NaN
7 1900-01-01 16:22:00            16.0
8 1900-01-01 16:45:00            16.0
9 1900-01-01 15:00:00            15.0

In [403]:
data["Discharge Before 12PM"] = np.where(
    data["Discharge Hour"].isna(),
    "Unknown",
    np.where(
        data["Discharge Hour"] < 12,
        "Yes",
        "No"
    )
)

In [404]:
data[["Discharge Time", "Discharge Hour", "Discharge Before 12PM"]].head(15)

        Discharge Time  Discharge Hour Discharge Before 12PM
0  1900-01-01 07:00:00             7.0                   Yes
1                  NaT             NaN               Unknown
2                  NaT             NaN               Unknown
3  1900-01-01 09:13:00             9.0                   Yes
4  1900-01-01 13:39:00            13.0                    No
5                  NaT             NaN               Unknown
6                  NaT             NaN               Unknown
7  1900-01-01 16:22:00            16.0                    No
8  1900-01-01 16:45:00            16.0                    No
9  1900-01-01 15:00:00            15.0                    No
10                 NaT             NaN               Unknown
11 1900-01-01 07:37:00             7.0                   Yes
12 1900-01-01 16:53:00            16.0                    No
13 1900-01-01 07:31:00             7.0                   Yes
14                 NaT             NaN               Unknown

In [405]:
data["Discharge Before 12PM"].value_counts()

Discharge Before 12PM
Unknown    238
No         141
Yes        121
Name: count, dtype: int64

In [406]:
data["Month"].dtype

dtype('O')

In [407]:
data["Month"].value_counts()

Month
01-02-2025    56
01-06-2025    56
01-10-2025    52
01-04-2025    47
01-12-2025    43
01-09-2025    42
01-07-2025    40
01-08-2025    37
01-03-2025    33
01-01-2025    33
01-05-2025    31
01-11-2025    30
Name: count, dtype: int64

In [408]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

Month                     0.0
Case_No                   0.0
DOB                       0.0
Nationality               0.0
Gender                    0.0
DoctorLicense             0.0
DoctorName                0.0
Doctor Type               0.0
Doctor Status             0.0
CMI Value                 0.0
Specialty                 0.0
Insurance/Payer           0.0
InsurancePlanName        14.4
Payer Mix                 0.0
Case type                 0.0
LOS                       0.0
Severity                  0.0
Surgical Mix              0.0
Discharge Time           47.6
Discharge Before 12PM    47.6
Revenue                   0.0
dtype: float64

In [409]:
df["InsurancePlanName"] = df["InsurancePlanName"].fillna(
    df["InsurancePlanName"].mode()[0]
)

In [410]:
print(df["Discharge Time"].dropna().head(10).to_list())

['07:00:00', '09:13:00', '13:39:00', '16:22:00', '16:45:00', '15:00:00', '07:37:00', '16:53:00', '07:31:00', '15:04:00']

In [411]:
df["Discharge Time"] = pd.to_datetime(
    df["Discharge Time"], format="%H:%M:%S", errors="coerce"
)

median_time = df["Discharge Time"].dropna().median()

df["Discharge Time"] = df["Discharge Time"].fillna(median_time)

df["Discharge Time"] = df["Discharge Time"].dt.strftime("%H:%M:%S")

In [412]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

Month                     0.0
Case_No                   0.0
DOB                       0.0
Nationality               0.0
Gender                    0.0
DoctorLicense             0.0
DoctorName                0.0
Doctor Type               0.0
Doctor Status             0.0
CMI Value                 0.0
Specialty                 0.0
Insurance/Payer           0.0
InsurancePlanName         0.0
Payer Mix                 0.0
Case type                 0.0
LOS                       0.0
Severity                  0.0
Surgical Mix              0.0
Discharge Time            0.0
Discharge Before 12PM    47.6
Revenue                   0.0
dtype: float64

In [413]:
df["Discharge Before 12PM"] = df["Discharge Before 12PM"].fillna(
    df["Discharge Before 12PM"].mode()[0]
)

In [414]:

df["InsurancePlanName"] = df["InsurancePlanName"].fillna(
    df["InsurancePlanName"].mode()[0]
)

df["Discharge Before 12PM"] = df["Discharge Before 12PM"].fillna(
    df["Discharge Before 12PM"].mode()[0]
)

In [415]:
print(df["Discharge Before 12PM"].value_counts(dropna=False))

Discharge Before 12PM
No     379
Yes    121
Name: count, dtype: int64

In [416]:
print(df.isnull().sum())

Month                    0
Case_No                  0
DOB                      0
Nationality              0
Gender                   0
DoctorLicense            0
DoctorName               0
Doctor Type              0
Doctor Status            0
CMI Value                0
Specialty                0
Insurance/Payer          0
InsurancePlanName        0
Payer Mix                0
Case type                0
LOS                      0
Severity                 0
Surgical Mix             0
Discharge Time           0
Discharge Before 12PM    0
Revenue                  0
dtype: int64

In [417]:
data.to_csv("hospital_cleaned_transformed_data.csv", index=False)

print("Dataset cleaned successfully")

Dataset cleaned successfully

In [418]:
print(df["InsurancePlanName"].value_counts(dropna=False))
print(df["Discharge Time"].value_counts(dropna=False))
print(df["Discharge Before 12PM"].value_counts(dropna=False))

InsurancePlanName
Advance        156
Premium         65
Basic           62
NC-Blue         43
GH-2            39
TH-Plus         39
GH-1            36
TH-Standard     33
NC-Gold         27
Name: count, dtype: int64
Discharge Time
13:00:30    238
07:00:00      2
11:20:00      2
10:23:00      2
07:38:00      2
           ...
14:00:00      1
16:27:00      1
07:26:00      1
11:37:00      1
09:07:00      1
Name: count, Length: 229, dtype: int64
Discharge Before 12PM
No     379
Yes    121
Name: count, dtype: int64

In [419]:
df["InsurancePlanName"] = df["InsurancePlanName"].fillna(
    df["InsurancePlanName"].mode()[0]
)

In [420]:
df["Discharge Time"] = pd.to_datetime(
    df["Discharge Time"],
    errors="coerce"
)

median_time = df["Discharge Time"].dropna().median()

df["Discharge Time"] = df["Discharge Time"].fillna(median_time)

C:\Users\Dell\AppData\Local\Temp\ipykernel_33564\2936214079.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Discharge Time"] = pd.to_datetime(

In [421]:
df["Discharge Before 12PM"] = df["Discharge Before 12PM"].fillna(
    df["Discharge Before 12PM"].mode()[0]
)

In [422]:
print(df.isnull().sum())

Month                    0
Case_No                  0
DOB                      0
Nationality              0
Gender                   0
DoctorLicense            0
DoctorName               0
Doctor Type              0
Doctor Status            0
CMI Value                0
Specialty                0
Insurance/Payer          0
InsurancePlanName        0
Payer Mix                0
Case type                0
LOS                      0
Severity                 0
Surgical Mix             0
Discharge Time           0
Discharge Before 12PM    0
Revenue                  0
dtype: int64

In [423]:
print("TOTAL EMPTY CELLS:", df.isnull().sum().sum())

TOTAL EMPTY CELLS: 0

In [424]:
df.to_csv("cleaned_hospital_data.csv", index=False)

In [425]:
# Hospital KPIs

total_cases = df["Case_No"].count()
total_revenue = df["Revenue"].sum()
average_revenue = df["Revenue"].mean()
average_los = df["LOS"].mean()
average_cmi = df["CMI Value"].mean()

print("===== HOSPITAL KPIs =====")
print("Total Cases       :", total_cases)
print("Total Revenue     :", round(total_revenue, 2))
print("Average Revenue   :", round(average_revenue, 2))
print("Average LOS       :", round(average_los, 2))
print("Average CMI Value :", round(average_cmi, 2))

===== HOSPITAL KPIs =====
Total Cases       : 500
Total Revenue     : 8523364
Average Revenue   : 17046.73
Average LOS       : 1.28
Average CMI Value : 1.04

In [426]:
kpis = pd.DataFrame({
    "KPI": [
        "Total Cases",
        "Total Revenue",
        "Average Revenue",
        "Average LOS",
        "Average CMI Value"
    ],
    "Value": [
        total_cases,
        total_revenue,
        average_revenue,
        average_los,
        average_cmi
    ]
})

kpis

                 KPI         Value
0        Total Cases  5.000000e+02
1      Total Revenue  8.523364e+06
2    Average Revenue  1.704673e+04
3        Average LOS  1.284000e+00
4  Average CMI Value  1.037098e+00

In [427]:
kpis.to_excel("hospital_kpis.xlsx", index=False)