In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [5]:
# LOAD DATASETS
hospital_patient = pd.read_csv(
    "Hospital Patient .csv"
)

patients = pd.read_csv(
    "patients.csv"
)

services_weekly = pd.read_csv(
    "services_weekly.csv"
)

staff = pd.read_csv(
    "staff.csv"
)

staff_schedule = pd.read_csv(
    "staff_schedule.csv"
)

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [7]:
# DATASET SHAPE BEFORE CLEANING

datasets = {
    "Hospital Patient": hospital_patient,
    "Patients": patients,
    "Services Weekly": services_weekly,
    "Staff": staff,
    "Staff Schedule": staff_schedule
}

print("DATASET INFORMATION BEFORE CLEANING")


for name, df in datasets.items():

    print(name)

    print("Rows    :", df.shape[0])
    print("Columns :", df.shape[1])

DATASET INFORMATION BEFORE CLEANING
Hospital Patient
Rows    : 984
Columns : 15
Patients
Rows    : 1000
Columns : 7
Services Weekly
Rows    : 208
Columns : 10
Staff
Rows    : 110
Columns : 4
Staff Schedule
Rows    : 6552
Columns : 6

In [9]:
# COLUMN INFORMATION
for name, df in datasets.items():
    print(name)
    for i, column in enumerate(df.columns, 1):
        print(f"{i}. {column}")

Hospital Patient
1. Patient_ID
2. Age
3. Gender
4. Condition
5. Medication
6. Admission_Date
7. Discharge_Date
8. Patient_State
9. Year_of_Admission
10. Length_of_Stay
11. Readmission
12. Outcome
13. Satisfaction
14. Insurance_Claimed
15. Total_Cost
Patients
1. patient_id
2. name
3. age
4. arrival_date
5. departure_date
6. service
7. satisfaction
Services Weekly
1. week
2. month
3. service
4. available_beds
5. patients_request
6. patients_admitted
7. patients_refused
8. patient_satisfaction
9. staff_morale
10. event
Staff
1. staff_id
2. staff_name
3. role
4. service
Staff Schedule
1. week
2. staff_id
3. staff_name
4. role
5. service
6. present

In [11]:
# NULL VALUE CHECK

print("=" * 70)
print("NULL VALUE ANALYSIS - BEFORE CLEANING")
print("=" * 70)

for name, df in datasets.items():

    print("\n" + "-" * 60)
    print(name)
    print("-" * 60)

    null_count = df.isnull().sum()

    null_report = pd.DataFrame({
        "Column": df.columns,
        "Null_Count": null_count.values,
        "Null_Percentage": (
            null_count.values / len(df) * 100
        ).round(2)
    })

    display(null_report)

======================================================================
NULL VALUE ANALYSIS - BEFORE CLEANING
======================================================================

------------------------------------------------------------
Hospital Patient
------------------------------------------------------------

               Column  Null_Count  Null_Percentage
0          Patient_ID           0              0.0
1                 Age           0              0.0
2              Gender           0              0.0
3           Condition           0              0.0
4         Medication            0              0.0
5      Admission_Date           0              0.0
6      Discharge_Date           0              0.0
7       Patient_State           0              0.0
8   Year_of_Admission           0              0.0
9      Length_of_Stay           0              0.0
10        Readmission           0              0.0
11            Outcome           0              0.0
12       Satisfaction           0              0.0
13  Insurance_Claimed           0              0.0
14         Total_Cost           0              0.0

------------------------------------------------------------
Patients
------------------------------------------------------------

           Column  Null_Count  Null_Percentage
0      patient_id           0              0.0
1            name           0              0.0
2             age           0              0.0
3    arrival_date           0              0.0
4  departure_date           0              0.0
5         service           0              0.0
6    satisfaction           0              0.0

------------------------------------------------------------
Services Weekly
------------------------------------------------------------

                 Column  Null_Count  Null_Percentage
0                  week           0              0.0
1                 month           0              0.0
2               service           0              0.0
3        available_beds           0              0.0
4      patients_request           0              0.0
5     patients_admitted           0              0.0
6      patients_refused           0              0.0
7  patient_satisfaction           0              0.0
8          staff_morale           0              0.0
9                 event           0              0.0

------------------------------------------------------------
Staff
------------------------------------------------------------

       Column  Null_Count  Null_Percentage
0    staff_id           0              0.0
1  staff_name           0              0.0
2        role           0              0.0
3     service           0              0.0

------------------------------------------------------------
Staff Schedule
------------------------------------------------------------

       Column  Null_Count  Null_Percentage
0        week           0              0.0
1    staff_id           0              0.0
2  staff_name           0              0.0
3        role           0              0.0
4     service           0              0.0
5     present           0              0.0

In [13]:
# DUPLICATE ROW CHECK

print("=" * 70)
print("DUPLICATE CHECK - BEFORE CLEANING")
print("=" * 70)

for name, df in datasets.items():

    duplicate_count = df.duplicated().sum()

    print(
        f"{name:<25} → {duplicate_count} duplicate rows"
    )

======================================================================
DUPLICATE CHECK - BEFORE CLEANING
======================================================================
Hospital Patient          → 0 duplicate rows
Patients                  → 0 duplicate rows
Services Weekly           → 0 duplicate rows
Staff                     → 0 duplicate rows
Staff Schedule            → 0 duplicate rows

In [15]:
# UNIQUE ID CHECK

print("=" * 70)
print("ID UNIQUENESS CHECK")
print("=" * 70)

print("\nHospital Patient")
print("Total IDs  :", hospital_patient["Patient_ID"].count())
print("Unique IDs :", hospital_patient["Patient_ID"].nunique())

print("\nPatients")
print("Total IDs  :", patients["patient_id"].count())
print("Unique IDs :", patients["patient_id"].nunique())

print("\nStaff")
print("Total IDs  :", staff["staff_id"].count())
print("Unique IDs :", staff["staff_id"].nunique())

======================================================================
ID UNIQUENESS CHECK
======================================================================

Hospital Patient
Total IDs  : 984
Unique IDs : 984

Patients
Total IDs  : 1000
Unique IDs : 1000

Staff
Total IDs  : 110
Unique IDs : 110

In [17]:
# CHECK COMMON SERVICE VALUES

print("=" * 70)
print("SERVICE VALUE CHECK")
print("=" * 70)

print("\nPatients:")
print(patients["service"].unique())

print("\nServices Weekly:")
print(services_weekly["service"].unique())

print("\nStaff:")
print(staff["service"].unique())

======================================================================
SERVICE VALUE CHECK
======================================================================

Patients:
['surgery' 'general_medicine' 'emergency' 'ICU']

Services Weekly:
['emergency' 'surgery' 'general_medicine' 'ICU']

Staff:
['emergency' 'surgery' 'general_medicine' 'ICU']

In [19]:
# STANDARDIZE COLUMN NAMES

def clean_column_names(df):

    df = df.copy()

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )

    return df


hospital_patient = clean_column_names(hospital_patient)
patients = clean_column_names(patients)
services_weekly = clean_column_names(services_weekly)
staff = clean_column_names(staff)
staff_schedule = clean_column_names(staff_schedule)

print("Column names standardized!")

Column names standardized!

In [21]:
# DATE CONVERSION

hospital_patient["admission_date"] = pd.to_datetime(
    hospital_patient["admission_date"],
    dayfirst=True,
    errors="coerce"
)

hospital_patient["discharge_date"] = pd.to_datetime(
    hospital_patient["discharge_date"],
    dayfirst=True,
    errors="coerce"
)

patients["arrival_date"] = pd.to_datetime(
    patients["arrival_date"],
    errors="coerce"
)

patients["departure_date"] = pd.to_datetime(
    patients["departure_date"],
    errors="coerce"
)

print("Date conversion completed!")

Date conversion completed!

In [23]:
# CHECK INVALID DATES

print("=" * 70)
print("DATE VALIDATION")
print("=" * 70)

print("\nHospital Patient:")
print(
    hospital_patient[
        ["admission_date", "discharge_date"]
    ].isnull().sum()
)

print("\nPatients:")
print(
    patients[
        ["arrival_date", "departure_date"]
    ].isnull().sum()
)

======================================================================
DATE VALIDATION
======================================================================

Hospital Patient:
admission_date    0
discharge_date    0
dtype: int64

Patients:
arrival_date      0
departure_date    0
dtype: int64

In [25]:
# SERVICE LEVEL AGGREGATION

service_summary = (
    services_weekly
    .groupby("service")
    .agg(
        total_available_beds=("available_beds", "sum"),
        total_patient_requests=("patients_request", "sum"),
        total_patients_admitted=("patients_admitted", "sum"),
        total_patients_refused=("patients_refused", "sum"),
        avg_patient_satisfaction=("patient_satisfaction", "mean"),
        avg_staff_morale=("staff_morale", "mean")
    )
    .reset_index()
)

print("=" * 70)
print("SERVICE SUMMARY")
print("=" * 70)

display(service_summary)

======================================================================
SERVICE SUMMARY
======================================================================

,service,total_available_beds,total_patient_requests,total_patients_admitted,total_patients_refused,avg_patient_satisfaction,avg_staff_morale
0,ICU,772,789,648,141,81.615385,70.980769
1,emergency,1185,6193,1185,5008,77.884615,73.557692
2,general_medicine,2404,4270,2332,1938,81.230769,73.096154
3,surgery,1951,2241,1686,555,79.269231,72.634615

In [27]:
# BED UTILIZATION

service_summary["bed_utilization_rate"] = (
    service_summary["total_patients_admitted"]
    /
    service_summary["total_available_beds"]
)

service_summary["bed_utilization_rate"] = (
    service_summary["bed_utilization_rate"]
    .clip(upper=1)
    .round(4)
)

display(service_summary)

,service,total_available_beds,total_patient_requests,total_patients_admitted,total_patients_refused,avg_patient_satisfaction,avg_staff_morale,bed_utilization_rate
0,ICU,772,789,648,141,81.615385,70.980769,0.8394
1,emergency,1185,6193,1185,5008,77.884615,73.557692,1.0000
2,general_medicine,2404,4270,2332,1938,81.230769,73.096154,0.9700
3,surgery,1951,2241,1686,555,79.269231,72.634615,0.8642

In [29]:
# STAFF SUMMARY

staff_summary = (
    staff
    .groupby("service")
    .agg(
        total_staff=("staff_id", "nunique"),
        doctors=("role", lambda x: (x == "doctor").sum()),
        nurses=("role", lambda x: (x == "nurse").sum())
    )
    .reset_index()
)

print("=" * 70)
print("STAFF SUMMARY")
print("=" * 70)

display(staff_summary)

======================================================================
STAFF SUMMARY
======================================================================

            service  total_staff  doctors  nurses
0               ICU           32        6      18
1         emergency           29        5      19
2  general_medicine           27        3      19
3           surgery           22        4      13

In [31]:
# STAFF ATTENDANCE SUMMARY

attendance_summary = (
    staff_schedule
    .groupby("service")
    .agg(
        total_staff_schedule_records=("staff_id", "count"),
        total_present=("present", "sum"),
        attendance_rate=("present", "mean")
    )
    .reset_index()
)

attendance_summary["attendance_rate"] = (
    attendance_summary["attendance_rate"] * 100
).round(2)

display(attendance_summary)

            service  total_staff_schedule_records  total_present  attendance_rate
0               ICU                          1768           1063            60.12
1         emergency                          2028           1225            60.40
2  general_medicine                          1456            859            59.00
3           surgery                          1300            783            60.23

In [33]:
# COMBINE SERVICE TABLES

service_operations = service_summary.merge(
    staff_summary,
    on="service",
    how="left"
)

service_operations = service_operations.merge(
    attendance_summary,
    on="service",
    how="left"
)

print("=" * 70)
print("COMBINED SERVICE OPERATIONS TABLE")
print("=" * 70)

print("Shape :", service_operations.shape)

display(service_operations)

======================================================================
COMBINED SERVICE OPERATIONS TABLE
======================================================================
Shape : (4, 14)

,service,total_available_beds,total_patient_requests,total_patients_admitted,total_patients_refused,avg_patient_satisfaction,avg_staff_morale,bed_utilization_rate,total_staff,doctors,nurses,total_staff_schedule_records,total_present,attendance_rate
0,ICU,772,789,648,141,81.615385,70.980769,0.8394,32,6,18,1768,1063,60.12
1,emergency,1185,6193,1185,5008,77.884615,73.557692,1.0000,29,5,19,2028,1225,60.40
2,general_medicine,2404,4270,2332,1938,81.230769,73.096154,0.9700,27,3,19,1456,859,59.00
3,surgery,1951,2241,1686,555,79.269231,72.634615,0.8642,22,4,13,1300,783,60.23

In [35]:
# CREATE FINAL PATIENT OPERATIONS DATASET

final_dataset = patients.merge(
    service_operations,
    on="service",
    how="left"
)

print("=" * 70)
print("FINAL COMBINED DATASET")
print("=" * 70)

print("Rows    :", final_dataset.shape[0])
print("Columns :", final_dataset.shape[1])

display(final_dataset.head())

======================================================================
FINAL COMBINED DATASET
======================================================================
Rows    : 1000
Columns : 20

,patient_id,name,age,arrival_date,departure_date,service,satisfaction,total_available_beds,total_patient_requests,total_patients_admitted,total_patients_refused,avg_patient_satisfaction,avg_staff_morale,bed_utilization_rate,total_staff,doctors,nurses,total_staff_schedule_records,total_present,attendance_rate
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61,1951,2241,1686,555,79.269231,72.634615,0.8642,22,4,13,1300,783,60.23
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83,1951,2241,1686,555,79.269231,72.634615,0.8642,22,4,13,1300,783,60.23
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83,2404,4270,2332,1938,81.230769,73.096154,0.9700,27,3,19,1456,859,59.00
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81,1185,6193,1185,5008,77.884615,73.557692,1.0000,29,5,19,2028,1225,60.40
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76,772,789,648,141,81.615385,70.980769,0.8394,32,6,18,1768,1063,60.12

In [37]:
# Check shape of newly created dataset

print("Shape of Newly Created Dataset:")
print(final_dataset.shape)

Shape of Newly Created Dataset:
(1000, 20)