In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("data/Hospital_Operations_Cleaned (1).csv")

In [ ]:
df.head()

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,...,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
0,2025-02-01,123517868.0,2002.0,Pakistan,F,ABC123,Dr. Shawn Martin,Consultant,Inactive,1.048,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,07:00:00,Yes,548.0
1,2025-10-01,123810649.0,1981.0,Indonesia,F,VBN123,Dr. Peter Novak,Consultant,Active,0.942,...,PureWin Insurance,Basic,Insurance,OP,0.0,2.0,Medical,06:41:00,No,1198.0
2,2025-08-01,123979661.0,1990.0,Egypt,M,FGH123,Dr. Sofia Kim,GP,Active,1.089,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,06:41:00,No,586.0
3,2025-06-01,123927914.0,1991.0,Germany,M,HJK123,Dr. Priya Iyer,Specialist,Active,0.970,...,BlueMedic Charity,Advance,Corporate,IP,5.0,1.0,Medical,09:13:00,Yes,28717.0
4,2025-06-01,123605097.0,2000.0,UAE,F,ABC234,Dr. Thomas Muller,Specialist,Active,1.006,...,Nextcare Insurance,NC-Blue,Insurance,IP,4.0,3.0,Medical,13:39:00,No,117129.0

In [ ]:
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

(500, 21)
Index(['Month', 'Case_No', 'DOB', 'Nationality', 'Gender', 'DoctorLicense',
       'DoctorName', 'Doctor Type', 'Doctor Status', 'CMI Value', 'Specialty',
       'Insurance/Payer', 'InsurancePlanName', 'Payer Mix', 'Case type', 'LOS',
       'Severity', 'Surgical Mix', 'Discharge Time', 'Discharge Before 12PM',
       'Revenue'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Month                  500 non-null    str
 1   Case_No                500 non-null    float64
 2   DOB                    500 non-null    float64
 3   Nationality            500 non-null    str
 4   Gender                 500 non-null    str
 5   DoctorLicense          500 non-null    str
 6   DoctorName             500 non-null    str
 7   Doctor Type            500 non-null    str
 8   Doctor Status          500 non-null    str
 9   CMI Value              500 non-null    float64
 10  Specialty              500 non-null    str
 11  Insurance/Payer        500 non-null    str
 12  InsurancePlanName      500 non-null    str
 13  Payer Mix              500 non-null    str
 14  Case type              500 non-null    str
 15  LOS                    500 non-null    float64
 16  Severity               500 non-null    float64
 17  Surgical Mix           500 non-null    str
 18  Discharge Time         500 non-null    str
 19  Discharge Before 12PM  500 non-null    str
 20  Revenue                500 non-null    float64
dtypes: float64(6), str(15)
memory usage: 82.2 KB
None
            Case_No          DOB   CMI Value      LOS    Severity  \
count  5.000000e+02   500.000000  500.000000  500.000  500.000000
mean   1.237317e+08  1984.408000    1.037098    1.284    1.782000
std    1.585829e+05    14.024225    0.110963    1.946    0.712384
min    1.234584e+08  1955.000000    0.710000    0.000    1.000000
25%    1.235896e+08  1975.000000    0.960000    0.000    1.000000
50%    1.237408e+08  1987.000000    1.035000    0.000    2.000000
75%    1.238734e+08  1996.000000    1.110250    3.000    2.000000
max    1.239995e+08  2005.000000    1.394000    7.000    3.000000

            Revenue
count     500.00000
mean    17046.72800
std     30527.29352
min        99.00000
25%       830.00000
50%      1628.50000
75%     15310.50000
max    160962.00000

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
categorical_columns = [
    "Nationality",
    "Gender",
    "Doctor Type",
    "Doctor Status",
    "Specialty",
    "Insurance/Payer",
    "InsurancePlanName",
    "Payer Mix",
    "Case type",
    "Surgical Mix",
    "Discharge Before 12PM"
]

for column in categorical_columns:
    print("\n==========", column, "==========")
    print(df[column].value_counts())

========== Nationality ==========
Nationality
India          101
UAE             85
Egypt           43
Philippines     43
Bangladesh      36
Pakistan        35
USA             31
Indonesia       29
Oman            24
Sri Lanka       19
Netherlands     15
Denmark         15
Germany         13
Japan           11
Name: count, dtype: int64

========== Gender ==========
Gender
M    290
F    210
Name: count, dtype: int64

========== Doctor Type ==========
Doctor Type
Specialist    236
Consultant    206
GP             58
Name: count, dtype: int64

========== Doctor Status ==========
Doctor Status
Active      405
Inactive     95
Name: count, dtype: int64

========== Specialty ==========
Specialty
General Surgery            70
Emergency                  68
Orthopaedics               68
Cardiology                 54
Pulmonology                54
Obstetrics & Gynecology    52
Nephrology                 47
Internal Medicine          31
Gastroenterology           29
Family Medicine            27
Name: count, dtype: int64

========== Insurance/Payer ==========
Insurance/Payer
PureWin Insurance        211
Goodhealth Insurance      75
TotalHealth Insurance     72
Nextcare Insurance        70
BlueMedic Charity         44
Self-Pay Corporate        28
Name: count, dtype: int64

========== InsurancePlanName ==========
InsurancePlanName
Advance        156
Premium         65
Basic           62
NC-Blue         43
GH-2            39
TH-Plus         39
GH-1            36
TH-Standard     33
NC-Gold         27
Name: count, dtype: int64

========== Payer Mix ==========
Payer Mix
Insurance    428
Corporate     72
Name: count, dtype: int64

========== Case type ==========
Case type
OP    308
IP    141
DC     51
Name: count, dtype: int64

========== Surgical Mix ==========
Surgical Mix
Medical    300
Surgery    200
Name: count, dtype: int64

========== Discharge Before 12PM ==========
Discharge Before 12PM
No     379
Yes    121
Name: count, dtype: int64

In [ ]:
print(df["Case type"].value_counts())

Case type
OP    308
IP    141
DC     51
Name: count, dtype: int64

In [ ]:
print(df["Doctor Status"].value_counts())
print(df["Gender"].value_counts())
print("LOS = 0:", (df["LOS"] == 0).sum())

Doctor Status
Active      405
Inactive     95
Name: count, dtype: int64
Gender
M    290
F    210
Name: count, dtype: int64
LOS = 0: 308

In [ ]:
print(df["Severity"].value_counts().sort_index())

Severity
1.0    193
2.0    223
3.0     84
Name: count, dtype: int64

In [ ]:
print(df["CMI Value"].sort_values().head(10))
print(df["CMI Value"].sort_values().tail(10))

6      0.710
122    0.750
147    0.771
482    0.777
396    0.796
472    0.805
239    0.811
256    0.815
102    0.818
437    0.824
Name: CMI Value, dtype: float64
289    1.255
53     1.261
467    1.261
276    1.266
346    1.279
70     1.283
214    1.294
274    1.333
164    1.370
227    1.394
Name: CMI Value, dtype: float64

In [ ]:
print(df[df["Revenue"] < 0])
print(df.nlargest(10, "Revenue")[["Case_No", "Case type", "LOS", "Revenue"]])
print(df["Month"].unique())
print(df["Discharge Time"].unique()[:20])

Empty DataFrame
Columns: [Month, Case_No, DOB, Nationality, Gender, DoctorLicense, DoctorName, Doctor Type, Doctor Status, CMI Value, Specialty, Insurance/Payer, InsurancePlanName, Payer Mix, Case type, LOS, Severity, Surgical Mix, Discharge Time, Discharge Before 12PM, Revenue]
Index: []

[0 rows x 21 columns]
         Case_No Case type  LOS   Revenue
171  123790221.0        IP  4.0  160962.0
421  123767392.0        IP  4.0  149242.0
163  123566107.0        IP  4.0  122019.0
342  123950732.0        IP  3.0  117884.0
4    123605097.0        IP  4.0  117129.0
80   123506766.0        IP  6.0  112466.0
149  123917616.0        IP  5.0  112249.0
214  123956543.0        IP  5.0  112061.0
272  123458660.0        IP  4.0  111745.0
228  123721576.0        IP  4.0  110590.0
<StringArray>
['2025-02-01', '2025-10-01', '2025-08-01', '2025-06-01', '2025-11-01',
 '2025-09-01', '2025-03-01', '2025-07-01', '2025-12-01', '2025-05-01',
 '2025-01-01', '2025-04-01']
Length: 12, dtype: str
<StringArray>
['07:00:00', '06:41:00', '09:13:00', '13:39:00', '16:22:00', '16:45:00',
 '15:00:00', '07:37:00', '16:53:00', '07:31:00', '15:04:00', '11:06:00',
 '08:15:00', '07:59:00', '11:36:00', '08:16:00', '09:37:00', '07:49:00',
 '14:00:00', '06:05:00']
Length: 20, dtype: str

In [ ]:
df.head()

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,...,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
0,2025-02-01,123517868.0,2002.0,Pakistan,F,ABC123,Dr. Shawn Martin,Consultant,Inactive,1.048,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,07:00:00,Yes,548.0
1,2025-10-01,123810649.0,1981.0,Indonesia,F,VBN123,Dr. Peter Novak,Consultant,Active,0.942,...,PureWin Insurance,Basic,Insurance,OP,0.0,2.0,Medical,06:41:00,No,1198.0
2,2025-08-01,123979661.0,1990.0,Egypt,M,FGH123,Dr. Sofia Kim,GP,Active,1.089,...,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,06:41:00,No,586.0
3,2025-06-01,123927914.0,1991.0,Germany,M,HJK123,Dr. Priya Iyer,Specialist,Active,0.970,...,BlueMedic Charity,Advance,Corporate,IP,5.0,1.0,Medical,09:13:00,Yes,28717.0
4,2025-06-01,123605097.0,2000.0,UAE,F,ABC234,Dr. Thomas Muller,Specialist,Active,1.006,...,Nextcare Insurance,NC-Blue,Insurance,IP,4.0,3.0,Medical,13:39:00,No,117129.0

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

print("\n--- Gender ---")
print(df["Gender"].value_counts())

print("\n--- Case Type ---")
print(df["Case type"].value_counts())

print("\n--- Doctor Status ---")
print(df["Doctor Status"].value_counts())

print("\n--- Doctor Type ---")
print(df["Doctor Type"].value_counts())

print("\n--- Specialty ---")
print(df["Specialty"].value_counts())

print("\n--- Nationality ---")
print(df["Nationality"].value_counts())

print("\n--- Payer Mix ---")
print(df["Payer Mix"].value_counts())

print("\n--- Surgical Mix ---")
print(df["Surgical Mix"].value_counts())

print("\n--- Discharge Before 12PM ---")
print(df["Discharge Before 12PM"].value_counts())

print("\n--- Severity ---")
print(df["Severity"].value_counts().sort_index())

print("\n--- LOS zero values ---")
print((df["LOS"] == 0).sum())

print("\n--- Negative LOS ---")
print((df["LOS"] < 0).sum())

print("\n--- Negative Revenue ---")
print((df["Revenue"] < 0).sum())

print("\n--- Month values ---")
print(df["Month"].value_counts().sort_index())

Duplicate rows: 0

--- Gender ---
Gender
M    290
F    210
Name: count, dtype: int64

--- Case Type ---
Case type
OP    308
IP    141
DC     51
Name: count, dtype: int64

--- Doctor Status ---
Doctor Status
Active      405
Inactive     95
Name: count, dtype: int64

--- Doctor Type ---
Doctor Type
Specialist    236
Consultant    206
GP             58
Name: count, dtype: int64

--- Specialty ---
Specialty
General Surgery            70
Emergency                  68
Orthopaedics               68
Cardiology                 54
Pulmonology                54
Obstetrics & Gynecology    52
Nephrology                 47
Internal Medicine          31
Gastroenterology           29
Family Medicine            27
Name: count, dtype: int64

--- Nationality ---
Nationality
India          101
UAE             85
Egypt           43
Philippines     43
Bangladesh      36
Pakistan        35
USA             31
Indonesia       29
Oman            24
Sri Lanka       19
Netherlands     15
Denmark         15
Germany         13
Japan           11
Name: count, dtype: int64

--- Payer Mix ---
Payer Mix
Insurance    428
Corporate     72
Name: count, dtype: int64

--- Surgical Mix ---
Surgical Mix
Medical    300
Surgery    200
Name: count, dtype: int64

--- Discharge Before 12PM ---
Discharge Before 12PM
No     379
Yes    121
Name: count, dtype: int64

--- Severity ---
Severity
1.0    193
2.0    223
3.0     84
Name: count, dtype: int64

--- LOS zero values ---
308

--- Negative LOS ---
0

--- Negative Revenue ---
0

--- Month values ---
Month
2025-01-01    33
2025-02-01    56
2025-03-01    33
2025-04-01    47
2025-05-01    31
2025-06-01    56
2025-07-01    40
2025-08-01    37
2025-09-01    42
2025-10-01    52
2025-11-01    30
2025-12-01    43
Name: count, dtype: int64

In [ ]:
df["Month"] = pd.to_datetime(df["Month"])
print(df["Month"].dtype)
print(df["Month"].head())

datetime64[us]
0   2025-02-01
1   2025-10-01
2   2025-08-01
3   2025-06-01
4   2025-06-01
Name: Month, dtype: datetime64[us]

In [ ]:
df.columns

Index(['Month', 'Case_No', 'DOB', 'Nationality', 'Gender', 'DoctorLicense',
       'DoctorName', 'Doctor Type', 'Doctor Status', 'CMI Value', 'Specialty',
       'Insurance/Payer', 'InsurancePlanName', 'Payer Mix', 'Case type', 'LOS',
       'Severity', 'Surgical Mix', 'Discharge Time', 'Discharge Before 12PM',
       'Revenue'],
      dtype='str')

In [ ]:
print(df["Discharge Time"].dtype)
df["Discharge Time"] = pd.to_datetime(
    df["Discharge Time"],
    format="%H:%M:%S"
).dt.time

print(df["Discharge Time"].dtype)
print(df["Discharge Time"].head())

str
object
0    07:00:00
1    06:41:00
2    06:41:00
3    09:13:00
4    13:39:00
Name: Discharge Time, dtype: object

In [ ]:
print(df["DOB"].dtype)
df["DOB"].head()

float64

0    2002.0
1    1981.0
2    1990.0
3    1991.0
4    2000.0
Name: DOB, dtype: float64

In [ ]:
df["DOB"] = df["DOB"].astype(int)
print(df["DOB"].head())

0    2002
1    1981
2    1990
3    1991
4    2000
Name: DOB, dtype: int64

In [ ]:
print(df.dtypes)

Month                    datetime64[us]
Case_No                         float64
DOB                               int64
Nationality                         str
Gender                              str
DoctorLicense                       str
DoctorName                          str
Doctor Type                         str
Doctor Status                       str
CMI Value                       float64
Specialty                           str
Insurance/Payer                     str
InsurancePlanName                   str
Payer Mix                           str
Case type                           str
LOS                             float64
Severity                        float64
Surgical Mix                        str
Discharge Time                   object
Discharge Before 12PM               str
Revenue                         float64
dtype: object

In [ ]:
print((df["Case_No"] % 1 == 0).all())
df["Case_No"] = df["Case_No"].astype(int)

print((df["Severity"] % 1 == 0).all())
df["Severity"] = df["Severity"].astype(int)

print(type(df["Discharge Time"].iloc[0]))

True
True
<class 'datetime.time'>

In [ ]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print(df[["Case_No", "DOB", "CMI Value", "LOS", "Severity", "Revenue"]].describe())

Missing values:
Month                    0
Case_No                  0
DOB                      0
Nationality              0
Gender                   0
DoctorLicense            0
DoctorName               0
Doctor Type              0
Doctor Status            0
CMI Value                0
Specialty                0
Insurance/Payer          0
InsurancePlanName        0
Payer Mix                0
Case type                0
LOS                      0
Severity                 0
Surgical Mix             0
Discharge Time           0
Discharge Before 12PM    0
Revenue                  0
dtype: int64

Duplicate rows:
0

Data types:
Month                    datetime64[us]
Case_No                           int64
DOB                               int64
Nationality                         str
Gender                              str
DoctorLicense                       str
DoctorName                          str
Doctor Type                         str
Doctor Status                       str
CMI Value                       float64
Specialty                           str
Insurance/Payer                     str
InsurancePlanName                   str
Payer Mix                           str
Case type                           str
LOS                             float64
Severity                          int64
Surgical Mix                        str
Discharge Time                   object
Discharge Before 12PM               str
Revenue                         float64
dtype: object
            Case_No          DOB   CMI Value      LOS    Severity  \
count  5.000000e+02   500.000000  500.000000  500.000  500.000000
mean   1.237317e+08  1984.408000    1.037098    1.284    1.782000
std    1.585829e+05    14.024225    0.110963    1.946    0.712384
min    1.234584e+08  1955.000000    0.710000    0.000    1.000000
25%    1.235896e+08  1975.000000    0.960000    0.000    1.000000
50%    1.237408e+08  1987.000000    1.035000    0.000    2.000000
75%    1.238734e+08  1996.000000    1.110250    3.000    2.000000
max    1.239995e+08  2005.000000    1.394000    7.000    3.000000

            Revenue
count     500.00000
mean    17046.72800
std     30527.29352
min        99.00000
25%       830.00000
50%      1628.50000
75%     15310.50000
max    160962.00000

In [ ]:
print(df["Case_No"].head())

0    123517868
1    123810649
2    123979661
3    123927914
4    123605097
Name: Case_No, dtype: int64

In [ ]:
df.to_csv(
    "data/Hospital_Operations_Cleaned_Final.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!