Import libraries

In [33]:
import pandas as pd
import numpy as np
from pathlib import Path

Load Dataset

In [34]:
from pathlib import Path

BASE_DIR = Path.cwd()

INPUT_FILE = BASE_DIR / "hospital_raw_data.csv"

df = pd.read_csv(INPUT_FILE)

print("Dataset loaded successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully
Rows: 45000
Columns: 33

In [35]:
df.head()

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,...,bed_status,disease_name,disease_category,Length_of_Stay_Days,Patient_Age,Age_Group,Admission_Month,Admission_Year,Admission_Quarter,Bed_Occupied_Flag
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,...,Available,Anemia,Hematological,2,65.0,61-75,2020-02,2020,1,0
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,...,Available,Fracture Femur,Orthopedic,10,34.0,31-45,2022-02,2022,1,0
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,...,Available,Chronic Obstructive Pulmonary Disease,Respiratory,6,77.0,76+,2021-02,2021,1,0
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,...,Available,Acute Myocardial Infarction,Cardiac,5,4.0,0-17,2021-12,2021,4,0
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,...,Available,Hypertension,Cardiac,5,7.0,0-17,2022-07,2022,3,0

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   admission_id         45000 non-null  int64
 1   admission_date       45000 non-null  str
 2   discharge_date       45000 non-null  str
 3   admission_type       45000 non-null  str
 4   admission_status     45000 non-null  str
 5   patient_id           45000 non-null  int64
 6   department_id        45000 non-null  int64
 7   ward_id              45000 non-null  int64
 8   bed_id               45000 non-null  int64
 9   disease_id           45000 non-null  int64
 10  gender               45000 non-null  str
 11  date_of_birth        45000 non-null  str
 12  blood_group          45000 non-null  str
 13  city                 45000 non-null  str
 14  contact_number       45000 non-null  str
 15  department_name      45000 non-null  str
 16  department_type      45000 non-null  str
 17  floor_number         45000 non-null  int64
 18  status               45000 non-null  str
 19  ward_name            45000 non-null  str
 20  ward_type            45000 non-null  str
 21  total_beds           45000 non-null  int64
 22  bed_number           45000 non-null  str
 23  bed_status           45000 non-null  str
 24  disease_name         45000 non-null  str
 25  disease_category     45000 non-null  str
 26  Length_of_Stay_Days  45000 non-null  int64
 27  Patient_Age          45000 non-null  float64
 28  Age_Group            43628 non-null  str
 29  Admission_Month      45000 non-null  str
 30  Admission_Year       45000 non-null  int64
 31  Admission_Quarter    45000 non-null  int64
 32  Bed_Occupied_Flag    45000 non-null  int64
dtypes: float64(1), int64(12), str(20)
memory usage: 11.3 MB

In [37]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 45000
Number of columns: 33

Check duplicate records

In [38]:
duplicate_count = df.duplicated().sum()

print("Duplicate records:", duplicate_count)

Duplicate records: 0

Remove duplicate records

In [39]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 45000

Check missing values

In [40]:
missing_count = df.isnull().sum()

missing_percentage = (
    df.isnull().mean() * 100
).round(2)

missing_report = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage
})

missing_report.sort_values(
    "Missing_Percentage",
    ascending=False
)

                     Missing_Count  Missing_Percentage
Age_Group                     1372                3.05
admission_id                     0                0.00
admission_date                   0                0.00
admission_type                   0                0.00
discharge_date                   0                0.00
patient_id                       0                0.00
department_id                    0                0.00
ward_id                          0                0.00
admission_status                 0                0.00
disease_id                       0                0.00
gender                           0                0.00
date_of_birth                    0                0.00
blood_group                      0                0.00
city                             0                0.00
contact_number                   0                0.00
department_name                  0                0.00
bed_id                           0                0.00
department_type                  0                0.00
floor_number                     0                0.00
ward_name                        0                0.00
status                           0                0.00
total_beds                       0                0.00
bed_number                       0                0.00
bed_status                       0                0.00
ward_type                        0                0.00
disease_name                     0                0.00
disease_category                 0                0.00
Length_of_Stay_Days              0                0.00
Patient_Age                      0                0.00
Admission_Month                  0                0.00
Admission_Year                   0                0.00
Admission_Quarter                0                0.00
Bed_Occupied_Flag                0                0.00

Standardize column name

In [41]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

df.columns.tolist()

['admission_id',
 'admission_date',
 'discharge_date',
 'admission_type',
 'admission_status',
 'patient_id',
 'department_id',
 'ward_id',
 'bed_id',
 'disease_id',
 'gender',
 'date_of_birth',
 'blood_group',
 'city',
 'contact_number',
 'department_name',
 'department_type',
 'floor_number',
 'status',
 'ward_name',
 'ward_type',
 'total_beds',
 'bed_number',
 'bed_status',
 'disease_name',
 'disease_category',
 'length_of_stay_days',
 'patient_age',
 'age_group',
 'admission_month',
 'admission_year',
 'admission_quarter',
 'bed_occupied_flag']

Standardize text columns

In [42]:
text_columns = df.select_dtypes(
    include=["object"]
).columns

for column in text_columns:
    df[column] = (
        df[column]
        .astype("string")
        .str.strip()
    )

print("Text values standardized.")

Text values standardized.

C:\Users\victus\AppData\Local\Temp\ipykernel_13304\581867436.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(

Standardize department names

In [43]:
if "department_name" in df.columns:

    df["department_name"] = (
        df["department_name"]
        .str.strip()
        .str.title()
    )

    print(
        df["department_name"]
        .value_counts()
    )

department_name
Surgery              10126
Emergency             8777
Pediatrics            8438
Internal Medicine     7695
Orthopedics           5924
Icu                   4040
Name: count, dtype: Int64

Standardize gender

In [44]:
if "gender" in df.columns:

    df["gender"] = (
        df["gender"]
        .str.strip()
        .str.title()
    )

    gender_mapping = {
        "M": "Male",
        "MALE": "Male",
        "F": "Female",
        "FEMALE": "Female",
        "O": "Other",
        "OTHER": "Other"
    }

    df["gender"] = df["gender"].replace(
        gender_mapping
    )

df["gender"].value_counts(dropna=False)

gender
Male      24031
Female    20058
Other       911
Name: count, dtype: Int64

Convert date columns

In [45]:
date_columns = [
    "admission_date",
    "discharge_date",
    "date_of_birth"
]

for column in date_columns:

    if column in df.columns:

        df[column] = pd.to_datetime(
            df[column],
            errors="coerce"
        )

df[date_columns].dtypes

admission_date    datetime64[us]
discharge_date    datetime64[us]
date_of_birth     datetime64[us]
dtype: object

Check invalid dates

In [46]:
if (
    "admission_date" in df.columns
    and "discharge_date" in df.columns
):

    invalid_dates = (
        df["discharge_date"]
        < df["admission_date"]
    )

    print(
        "Invalid discharge dates:",
        invalid_dates.sum()
    )

Invalid discharge dates: 0

Correct invalid dates

In [47]:
if (
    "admission_date" in df.columns
    and "discharge_date" in df.columns
):

    invalid_dates = (
        df["discharge_date"]
        < df["admission_date"]
    )

    df.loc[
        invalid_dates,
        "discharge_date"
    ] = pd.NaT

Calculate Length of Stay

In [48]:
if (
    "admission_date" in df.columns
    and "discharge_date" in df.columns
):

    df["length_of_stay_days"] = (
        df["discharge_date"]
        - df["admission_date"]
    ).dt.days

df["length_of_stay_days"].describe()

count    45000.000000
mean         5.155000
std          3.271284
min          1.000000
25%          3.000000
50%          4.000000
75%          8.000000
max         15.000000
Name: length_of_stay_days, dtype: float64

Handle invalid Length of Stay

In [49]:
if "length_of_stay_days" in df.columns:

    df.loc[
        df["length_of_stay_days"] < 0,
        "length_of_stay_days"
    ] = np.nan

print(
    "Invalid LOS values:",
    df["length_of_stay_days"].isna().sum()
)

Invalid LOS values: 0

Calculate patient age

In [50]:
if (
    "admission_date" in df.columns
    and "date_of_birth" in df.columns
):

    df["patient_age"] = (
        (
            df["admission_date"]
            - df["date_of_birth"]
        ).dt.days / 365.25
    ).round(0)

df["patient_age"].describe()

count    45000.000000
mean        42.067511
std         26.418827
min         -6.000000
25%         19.000000
50%         42.000000
75%         65.000000
max         91.000000
Name: patient_age, dtype: float64

Validate patient age

In [51]:
if "patient_age" in df.columns:

    invalid_age = (
        (df["patient_age"] < 0)
        | (df["patient_age"] > 120)
    )

    print(
        "Invalid age values:",
        invalid_age.sum()
    )

    df.loc[
        invalid_age,
        "patient_age"
    ] = np.nan

Invalid age values: 1372

Create age groups

In [52]:
if "patient_age" in df.columns:

    df["age_group"] = pd.cut(
        df["patient_age"],
        bins=[0, 17, 30, 45, 60, 75, 120],
        labels=[
            "0-17",
            "18-30",
            "31-45",
            "46-60",
            "61-75",
            "76+"
        ],
        include_lowest=True
    )

df["age_group"].value_counts()

age_group
0-17     9045
61-75    7492
31-45    7452
46-60    7235
18-30    6386
76+      6018
Name: count, dtype: int64

Create time variables

In [53]:
if "admission_date" in df.columns:

    df["admission_year"] = (
        df["admission_date"].dt.year
    )

    df["admission_month"] = (
        df["admission_date"].dt.month
    )

    df["admission_month_name"] = (
        df["admission_date"].dt.month_name()
    )

    df["admission_quarter"] = (
        "Q"
        + df["admission_date"]
        .dt.quarter
        .astype("string")
    )

df[
    [
        "admission_year",
        "admission_month",
        "admission_month_name",
        "admission_quarter"
    ]
].head()

   admission_year  admission_month admission_month_name admission_quarter
0            2020                2             February                Q1
1            2022                2             February                Q1
2            2021                2             February                Q1
3            2021               12             December                Q4
4            2022                7                 July                Q3

Handle missing categorical values

In [54]:
categorical_columns = df.select_dtypes(
    include=["object", "string", "category"]
).columns

for column in categorical_columns:

    if df[column].isna().sum() > 0:

        df[column] = (
            df[column]
            .astype("string")
            .fillna("Unknown")
        )

print("Categorical missing values handled.")

Categorical missing values handled.

Handle missing numeric values

In [55]:
numeric_columns = df.select_dtypes(
    include=["number"]
).columns

for column in numeric_columns:

    if df[column].isna().sum() > 0:

        median_value = df[column].median()

        df[column] = df[column].fillna(
            median_value
        )

print("Numeric missing values handled.")

Numeric missing values handled.

Check missing values again

In [56]:
final_missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().mean() * 100
    ).round(2)
})

final_missing.sort_values(
    "Missing_Percentage",
    ascending=False
)

                      Missing_Count  Missing_Percentage
admission_id                      0                 0.0
admission_date                    0                 0.0
discharge_date                    0                 0.0
admission_type                    0                 0.0
admission_status                  0                 0.0
patient_id                        0                 0.0
department_id                     0                 0.0
ward_id                           0                 0.0
bed_id                            0                 0.0
disease_id                        0                 0.0
gender                            0                 0.0
date_of_birth                     0                 0.0
blood_group                       0                 0.0
city                              0                 0.0
contact_number                    0                 0.0
department_name                   0                 0.0
department_type                   0                 0.0
floor_number                      0                 0.0
status                            0                 0.0
ward_name                         0                 0.0
ward_type                         0                 0.0
total_beds                        0                 0.0
bed_number                        0                 0.0
bed_status                        0                 0.0
disease_name                      0                 0.0
disease_category                  0                 0.0
length_of_stay_days               0                 0.0
patient_age                       0                 0.0
age_group                         0                 0.0
admission_month                   0                 0.0
admission_year                    0                 0.0
admission_quarter                 0                 0.0
bed_occupied_flag                 0                 0.0
admission_month_name              0                 0.0

Check the required <2% condition

In [57]:
total_cells = df.shape[0] * df.shape[1]

total_missing = df.isnull().sum().sum()

overall_missing_percentage = (
    total_missing / total_cells
) * 100

print(
    f"Overall missing percentage: "
    f"{overall_missing_percentage:.2f}%"
)

if overall_missing_percentage < 2:
    print("PASS: Missing values are below 2%.")
else:
    print("REVIEW: Missing values are 2% or higher.")

Overall missing percentage: 0.00%
PASS: Missing values are below 2%.

Final duplicate check

In [58]:
print(
    "Remaining duplicate rows:",
    df.duplicated().sum()
)

Remaining duplicate rows: 0

Final dataset inspection

In [59]:
print("Final rows:", df.shape[0])
print("Final columns:", df.shape[1])

df.head()

Final rows: 45000
Final columns: 34

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,department_id,ward_id,bed_id,disease_id,...,disease_name,disease_category,length_of_stay_days,patient_age,age_group,admission_month,admission_year,admission_quarter,bed_occupied_flag,admission_month_name
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,2,6,76,10,...,Anemia,Hematological,2.0,65.0,61-75,2,2020,Q1,0,February
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,5,21,302,11,...,Fracture Femur,Orthopedic,10.0,34.0,31-45,2,2022,Q1,0,February
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,1,2,11,9,...,Chronic Obstructive Pulmonary Disease,Respiratory,6.0,77.0,76+,2,2021,Q1,0,February
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,2,10,128,1,...,Acute Myocardial Infarction,Cardiac,5.0,4.0,0-17,12,2021,Q4,0,December
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,3,11,157,7,...,Hypertension,Cardiac,5.0,7.0,0-17,7,2022,Q3,0,July

Save

In [63]:
OUTPUT_FILE = BASE_DIR / "hospital_cleaned.csv"

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print(
    "Cleaned dataset saved successfully:"
)

print(OUTPUT_FILE)

Cleaned dataset saved successfully:
e:\info intern\hospital_cleaned.csv